<?php
$helmets = [
    [
        "name" => "crown",
        "clientid" => "3011",
        "weight" => "1900",
        "slottype" => "head",
        "raritytier" => "4",
    ],
    [
        "name" => "ancient tiara",
        "clientid" => "3022",
        "weight" => "820",
        "slottype" => "head",
        "raritytier" => "4",
    ],
    [
        "name" => "hat of the mad",
        "clientid" => "3210",
        "weight" => "700",
        "armor" => "3",
        "slottype" => "head",
        "raritytier" => "4",
    ],
    [
        "name" => "damaged helmet",
        "clientid" => "3226",
        "weight" => "1800",
        "armor" => "5",
        "slottype" => "head",
    ],
    [
        "name" => "helmet of the ancients",
        "clientid" => "3229",
        "weight" => "2760",
        "armor" => "8",
        "slottype" => "head",
        "raritytier" => "4",
    ],
    [
        "name" => "helmet of the ancients",
        "clientid" => "3230",
        "weight" => "2760",
        "armor" => "11",
        "slottype" => "head",
        "duration" => "1800",
    ],
    [
        "name" => "steel helmet",
        "clientid" => "3351",
        "weight" => "4600",
        "armor" => "6",
        "slottype" => "head",
    ],
    [
        "name" => "chain helmet",
        "clientid" => "3352",
        "weight" => "4200",
        "armor" => "2",
        "slottype" => "head",
    ],
    [
        "name" => "iron helmet",
        "clientid" => "3353",
        "weight" => "3000",
        "armor" => "5",
        "slottype" => "head",
    ],
    [
        "name" => "brass helmet",
        "clientid" => "3354",
        "weight" => "2700",
        "armor" => "3",
        "slottype" => "head",
    ],
    [
        "name" => "leather helmet",
        "clientid" => "3355",
        "weight" => "2200",
        "armor" => "1",
        "slottype" => "head",
    ],
    [
        "name" => "devil helmet",
        "clientid" => "3356",
        "weight" => "5000",
        "armor" => "7",
        "slottype" => "head",
    ],
    [
        "name" => "golden helmet",
        "clientid" => "3365",
        "weight" => "3200",
        "armor" => "12",
        "slottype" => "head",
    ],
    [
        "name" => "viking helmet",
        "clientid" => "3367",
        "weight" => "3900",
        "armor" => "4",
        "slottype" => "head",
    ],
    [
        "name" => "winged helmet",
        "clientid" => "3368",
        "weight" => "1200",
        "armor" => "10",
        "slottype" => "head",
        "raritytier" => "4",
    ],
    [
        "name" => "warrior helmet",
        "clientid" => "3369",
        "weight" => "6800",
        "armor" => "8",
        "slottype" => "head",
    ],
    [
        "name" => "strange helmet",
        "clientid" => "3373",
        "weight" => "4600",
        "armor" => "6",
        "slottype" => "head",
    ],
    [
        "name" => "legion helmet",
        "clientid" => "3374",
        "weight" => "3100",
        "armor" => "4",
        "slottype" => "head",
    ],
    [
        "name" => "soldier helmet",
        "clientid" => "3375",
        "weight" => "3200",
        "armor" => "5",
        "slottype" => "head",
    ],
    [
        "name" => "studded helmet",
        "clientid" => "3376",
        "weight" => "2450",
        "armor" => "2",
        "slottype" => "head",
    ],
    [
        "name" => "dark helmet",
        "clientid" => "3384",
        "weight" => "4600",
        "armor" => "6",
        "slottype" => "head",
    ],
    [
        "name" => "crown helmet",
        "clientid" => "3385",
        "weight" => "2950",
        "armor" => "7",
        "slottype" => "head",
    ],
    [
        "name" => "demon helmet",
        "clientid" => "3387",
        "weight" => "2950",
        "armor" => "10",
        "absorbpercentfire" => "2",
        "slottype" => "head",
    ],
    [
        "name" => "horned helmet",
        "clientid" => "3390",
        "weight" => "5100",
        "armor" => "11",
        "slottype" => "head",
    ],
    [
        "name" => "crusader helmet",
        "clientid" => "3391",
        "weight" => "5200",
        "armor" => "8",
        "slottype" => "head",
    ],
    [
        "name" => "royal helmet",
        "clientid" => "3392",
        "weight" => "4800",
        "armor" => "9",
        "slottype" => "head",
    ],
    [
        "name" => "amazon helmet",
        "clientid" => "3393",
        "weight" => "2950",
        "armor" => "7",
        "slottype" => "head",
    ],
    [
        "name" => "ceremonial mask",
        "clientid" => "3395",
        "weight" => "4000",
        "armor" => "9",
        "slottype" => "head",
        "lightlevel" => "3",
    ],
    [
        "name" => "dwarfen helmet",
        "clientid" => "3396",
        "weight" => "4200",
        "armor" => "6",
        "slottype" => "head",
        "absorbpercentphysical" => "2",
        "raritytier" => "2",
    ],
    [
        "name" => "dragon scale helmet",
        "clientid" => "3400",
        "weight" => "3250",
        "armor" => "9",
        "slottype" => "head",
        "raritytier" => "4",
    ],
    [
        "name" => "magician hat",
        "clientid" => "3573",
        "weight" => "750",
        "armor" => "1",
        "slottype" => "head",
        "raritytier" => "4",
    ],
    [
        "name" => "mystic turban",
        "clientid" => "3574",
        "weight" => "850",
        "armor" => "1",
        "slottype" => "head",
    ],
    [
        "name" => "wood cape",
        "clientid" => "3575",
        "weight" => "1100",
        "armor" => "2",
        "slottype" => "head",
        "absorbpercentpoison" => "4",
    ],
    [
        "name" => "post officers hat",
        "clientid" => "3576",
        "weight" => "700",
        "armor" => "1",
        "slottype" => "head",
    ],
    [
        "name" => "tribal mask",
        "clientid" => "3403",
        "weight" => "2500",
        "armor" => "2",
        "slottype" => "head",
    ],
    [
        "name" => "horseman helmet",
        "clientid" => "3405",
        "weight" => "4200",
        "armor" => "6",
        "slottype" => "head",
    ],
    [
        "name" => "feather headdress",
        "clientid" => "3406",
        "weight" => "2100",
        "armor" => "2",
        "slottype" => "head",
        "raritytier" => "4",
    ],
    [
        "name" => "charmer's tiara",
        "clientid" => "3407",
        "weight" => "2200",
        "armor" => "2",
        "slottype" => "head",
        "raritytier" => "4",
    ],
    [
        "name" => "beholder helmet",
        "clientid" => "3408",
        "weight" => "4600",
        "armor" => "7",
        "slottype" => "head",
    ],
    [
        "name" => "santa's hat",
        "clientid" => "5238",
        "weight" => "700",
        "armor" => "1",
        "slottype" => "head",
    ],
];

$amors = [
    [
        "name" => "plate armor",
        "clientid" => "3357",
        "weight" => "12000",
        "armor" => "10",
        "slottype" => "body",
    ],
    [
        "name" => "chain armor",
        "clientid" => "3358",
        "weight" => "10000",
        "armor" => "6",
        "slottype" => "body",
    ],
    [
        "name" => "brass armor",
        "clientid" => "3359",
        "weight" => "8000",
        "armor" => "8",
        "slottype" => "body",
    ],
    [
        "name" => "golden armor",
        "clientid" => "3360",
        "weight" => "8000",
        "armor" => "14",
        "slottype" => "body",
    ],
    [
        "name" => "leather armor",
        "clientid" => "3361",
        "weight" => "6000",
        "armor" => "4",
        "slottype" => "body",
    ],
    [
        "name" => "magic plate armor",
        "clientid" => "3366",
        "weight" => "8500",
        "armor" => "17",
        "slottype" => "body",
    ],
    [
        "name" => "knight armor",
        "clientid" => "3370",
        "weight" => "12000",
        "armor" => "12",
        "slottype" => "body",
    ],
    [
        "name" => "scale armor",
        "clientid" => "3377",
        "weight" => "10500",
        "armor" => "9",
        "slottype" => "body",
    ],
    [
        "name" => "studded armor",
        "clientid" => "3378",
        "weight" => "7100",
        "armor" => "5",
        "slottype" => "body",
    ],
    [
        "name" => "doublet",
        "clientid" => "3379",
        "weight" => "2500",
        "armor" => "2",
        "slottype" => "body",
    ],
    [
        "name" => "noble armor",
        "clientid" => "3380",
        "weight" => "12000",
        "armor" => "11",
        "slottype" => "body",
    ],
    [
        "name" => "crown armor",
        "clientid" => "3381",
        "weight" => "9900",
        "armor" => "13",
        "slottype" => "body",
    ],
    [
        "name" => "dark armor",
        "clientid" => "3383",
        "weight" => "12000",
        "armor" => "10",
        "slottype" => "body",
    ],
    [
        "name" => "dragon scale mail",
        "clientid" => "3386",
        "weight" => "11400",
        "armor" => "15",
        "slottype" => "body",
    ],
    [
        "name" => "demon armor",
        "clientid" => "3388",
        "weight" => "8000",
        "armor" => "16",
        "absorbpercentfire" => "3",
        "slottype" => "body",
    ],
    [
        "name" => "amazon armor",
        "clientid" => "3394",
        "weight" => "9900",
        "armor" => "13",
        "slottype" => "body",
    ],
    [
        "name" => "dwarven armor",
        "clientid" => "3397",
        "weight" => "13000",
        "armor" => "10",
        "slottype" => "body",
        "absorbpercentphysical" => "5",
        "raritytier" => "2",
    ],
    [
        "name" => "elven mail",
        "clientid" => "3399",
        "weight" => "9000",
        "armor" => "10",
        "slottype" => "body",
        "absorbpercentlifedrain" => "3",
        "absorbpercentmanadrain" => "2",
        "raritytier" => "2",
    ],
    [
        "name" => "native armor",
        "clientid" => "3402",
        "weight" => "8000",
        "armor" => "11",
        "slottype" => "body",
    ],
    [
        "name" => "jacket",
        "clientid" => "3561",
        "weight" => "2400",
        "armor" => "1",
        "slottype" => "body",
    ],
    [
        "name" => "coat",
        "clientid" => "3562",
        "weight" => "2700",
        "armor" => "1",
        "slottype" => "body",
    ],
    [
        "name" => "green tunic",
        "clientid" => "3563",
        "weight" => "930",
        "armor" => "1",
        "slottype" => "body",
    ],
    [
        "name" => "red tunic",
        "clientid" => "3564",
        "weight" => "1400",
        "armor" => "2",
        "slottype" => "body",
    ],
    [
        "name" => "cape",
        "clientid" => "3565",
        "weight" => "3200",
        "armor" => "1",
        "slottype" => "body",
    ],
    [
        "name" => "red robe",
        "clientid" => "3566",
        "weight" => "2600",
        "armor" => "1",
        "slottype" => "body",
    ],
    [
        "name" => "blue robe",
        "clientid" => "3567",
        "weight" => "2200",
        "armor" => "11",
        "slottype" => "body",
    ],
    [
        "name" => "simple dress",
        "clientid" => "3568",
        "weight" => "2400",
        "slottype" => "body",
    ],
    [
        "name" => "white dress",
        "clientid" => "3569",
        "weight" => "2400",
        "slottype" => "body",
    ],
    [
        "name" => "ball gown",
        "clientid" => "3570",
        "weight" => "2500",
        "slottype" => "body",
    ],
    [
        "name" => "rangers cloak",
        "clientid" => "3571",
        "weight" => "3200",
        "armor" => "1",
        "slottype" => "body",
    ],
    [
        "name" => "leopard armor",
        "clientid" => "3404",
        "weight" => "9500",
        "armor" => "9",
        "slottype" => "body",
    ],
    [
        "name" => "spectral dress",
        "clientid" => "4836",
        "weight" => "1000",
        "slottype" => "body",
    ],
];

$legs = [
    [
        "name" => "studded legs",
        "clientid" => "3362",
        "weight" => "2600",
        "armor" => "2",
        "slottype" => "legs",
    ],
    [
        "name" => "dragon scale legs",
        "clientid" => "3363",
        "weight" => "4800",
        "armor" => "10",
        "slottype" => "legs",
    ],
    [
        "name" => "golden legs",
        "clientid" => "3364",
        "weight" => "5600",
        "armor" => "9",
        "slottype" => "legs",
    ],
    [
        "name" => "knight legs",
        "clientid" => "3371",
        "weight" => "7000",
        "armor" => "8",
        "slottype" => "legs",
    ],
    [
        "name" => "brass legs",
        "clientid" => "3372",
        "weight" => "3800",
        "armor" => "5",
        "slottype" => "legs",
    ],
    [
        "name" => "crown legs",
        "clientid" => "3382",
        "weight" => "6500",
        "armor" => "8",
        "slottype" => "legs",
    ],
    [
        "name" => "demon legs",
        "clientid" => "3389",
        "weight" => "7000",
        "armor" => "9",
        "absorbpercentfire" => "5",
        "slottype" => "legs",
        "raritytier" => "4",
    ],
    [
        "name" => "dwarfen legs",
        "clientid" => "3398",
        "weight" => "4900",
        "armor" => "6",
        "slottype" => "legs",
        "absorbpercentphysical" => "3",
        "raritytier" => "2",
    ],
    [
        "name" => "elven legs",
        "clientid" => "3401",
        "weight" => "3300",
        "armor" => "6",
        "slottype" => "legs",
        "absorbpercentlifedrain" => "2",
        "absorbpercentmanadrain" => "3",
        "raritytier" => "2",
    ],
    [
        "name" => "plate legs",
        "clientid" => "3557",
        "weight" => "5000",
        "armor" => "7",
        "slottype" => "legs",
    ],
    [
        "name" => "chain legs",
        "clientid" => "3558",
        "weight" => "3500",
        "armor" => "3",
        "slottype" => "legs",
    ],
    [
        "name" => "leather legs",
        "clientid" => "3559",
        "weight" => "1800",
        "armor" => "1",
        "slottype" => "legs",
    ],
    [
        "name" => "bast skirt",
        "clientid" => "3560",
        "weight" => "350",
        "slottype" => "legs",
    ],
];

$boots = [
    [
        "name" => "boots of haste",
        "clientid" => "3079",
        "weight" => "750",
        "slottype" => "feet",
    ],
    [
        "name" => "boots of waterwalking",
        "clientid" => "3246",
        "weight" => "770",
        "slottype" => "feet",
    ],
    [
        "name" => "soft boots",
        "clientid" => "3549",
        "weight" => "800",
        "slottype" => "feet",
        "healthgain" => "3",
        "healthticks" => "6000",
        "managain" => "12",
        "manaticks" => "6000",
    ],
    [
        "name" => "patched boots",
        "clientid" => "3550",
        "weight" => "1000",
        "armor" => "2",
        "slottype" => "feet",
    ],
    [
        "name" => "sandals",
        "clientid" => "3551",
        "weight" => "600",
        "slottype" => "feet",
    ],
    [
        "name" => "leather boots",
        "clientid" => "3552",
        "weight" => "900",
        "armor" => "1",
        "slottype" => "feet",
    ],
    [
        "name" => "bunnyslippers",
        "clientid" => "3553",
        "weight" => "600",
        "slottype" => "feet",
    ],
    [
        "name" => "steel boots",
        "clientid" => "3554",
        "weight" => "2900",
        "armor" => "3",
        "slottype" => "feet",
    ],
    [
        "name" => "golden boots",
        "clientid" => "3555",
        "weight" => "3100",
        "armor" => "4",
        "slottype" => "feet",
    ],
    [
        "name" => "crocodile boots",
        "clientid" => "3556",
        "weight" => "900",
        "armor" => "1",
        "slottype" => "feet",
    ],
];

$amulets = [
    [
        "name" => "crystal necklace",
        "clientid" => "3008",
        "weight" => "490",
        "slottype" => "necklace",
    ],
    [
        "name" => "bronze necklace",
        "clientid" => "3009",
        "weight" => "410",
        "slottype" => "necklace",
    ],
    [
        "name" => "wolf tooth chain",
        "clientid" => "3012",
        "weight" => "330",
        "slottype" => "necklace",
    ],
    [
        "name" => "golden amulet",
        "clientid" => "3013",
        "weight" => "830",
        "slottype" => "necklace",
    ],
    [
        "name" => "star amulet",
        "clientid" => "3014",
        "weight" => "610",
        "slottype" => "necklace",
    ],
    [
        "name" => "silver necklace",
        "clientid" => "3015",
        "weight" => "480",
        "slottype" => "necklace",
    ],
    [
        "name" => "ruby necklace",
        "clientid" => "3016",
        "weight" => "570",
        "slottype" => "necklace",
    ],
    [
        "name" => "scarab amulet",
        "clientid" => "3018",
        "weight" => "770",
        "slottype" => "necklace",
    ],
    [
        "name" => "demonbone amulet",
        "clientid" => "3019",
        "weight" => "690",
        "slottype" => "necklace",
    ],
    [
        "name" => "saphire amulet",
        "clientid" => "3021",
        "weight" => "680",
        "slottype" => "necklace",
    ],
    [
        "name" => "ancient amulet",
        "clientid" => "3025",
        "weight" => "840",
        "slottype" => "necklace",
    ],
    [
        "name" => "strange talisman",
        "clientid" => "3045",
        "weight" => "290",
        "slottype" => "necklace",
        "charges" => "200",
        "absorbpercentenergy" => "10",
    ],
    [
        "name" => "silver amulet",
        "clientid" => "3054",
        "weight" => "500",
        "slottype" => "necklace",
        "charges" => "200",
        "absorbpercentpoison" => "10",
    ],
    [
        "name" => "platinum amulet",
        "clientid" => "3055",
        "weight" => "600",
        "armor" => "2",
        "slottype" => "necklace",
    ],
    [
        "name" => "bronze amulet",
        "clientid" => "3056",
        "weight" => "500",
        "slottype" => "necklace",
        "charges" => "200",
        "absorbpercentmanadrain" => "20",
    ],
    [
        "name" => "amulet of loss",
        "clientid" => "3057",
        "weight" => "420",
        "slottype" => "necklace",
    ],
    [
        "name" => "broken amulet",
        "clientid" => "3080",
        "weight" => "420",
        "slottype" => "necklace",
    ],
    [
        "name" => "stone skin amulet",
        "clientid" => "3081",
        "weight" => "700",
        "slottype" => "necklace",
        "charges" => "5",
        "absorbpercentphysical" => "80",
    ],
    [
        "name" => "elven amulet",
        "clientid" => "3082",
        "weight" => "270",
        "slottype" => "necklace",
        "charges" => "50",
        "absorbpercentphysical" => "5",
        "absorbpercentenergy" => "5",
        "absorbpercentfire" => "5",
        "absorbpercentpoison" => "5",
    ],
    [
        "name" => "garlic necklace",
        "clientid" => "3083",
        "weight" => "380",
        "slottype" => "necklace",
        "charges" => "150",
        "absorbpercentlifedrain" => "20",
    ],
    [
        "name" => "protection amulet",
        "clientid" => "3084",
        "weight" => "550",
        "slottype" => "necklace",
        "charges" => "250",
        "absorbpercentphysical" => "6",
    ],
    [
        "name" => "dragon necklace",
        "clientid" => "3085",
        "weight" => "630",
        "slottype" => "necklace",
        "charges" => "200",
        "absorbpercentfire" => "8",
    ],
    [
        "name" => "paw amulet",
        "clientid" => "3102",
        "weight" => "420",
        "slottype" => "necklace",
    ],
    [
        "name" => "scarf",
        "clientid" => "3572",
        "weight" => "200",
        "armor" => "1",
        "slottype" => "necklace",
    ],
];

$rings = [
    [
        "name" => "wedding ring",
        "clientid" => "3004",
        "weight" => "40",
        "slottype" => "ring",
    ],
    [
        "name" => "ring of the sky",
        "clientid" => "3006",
        "weight" => "40",
        "slottype" => "ring",
    ],
    [
        "name" => "crystal ring",
        "clientid" => "3007",
        "weight" => "90",
        "slottype" => "ring",
    ],
    [
        "name" => "might ring",
        "clientid" => "3048",
        "weight" => "100",
        "slottype" => "ring",
        "charges" => "20",
        "absorbpercentphysical" => "20",
        "absorbpercentenergy" => "20",
        "absorbpercentfire" => "20",
        "absorbpercentpoison" => "20",
    ],
    [
        "name" => "stealth ring",
        "clientid" => "3049",
        "weight" => "100",
        "slottype" => "ring",
    ],
    [
        "name" => "power ring",
        "clientid" => "3050",
        "weight" => "80",
        "slottype" => "ring",
    ],
    [
        "name" => "energy ring",
        "clientid" => "3051",
        "weight" => "80",
        "slottype" => "ring",
    ],
    [
        "name" => "life ring",
        "clientid" => "3052",
        "weight" => "80",
        "slottype" => "ring",
    ],
    [
        "name" => "time ring",
        "clientid" => "3053",
        "weight" => "90",
        "slottype" => "ring",
    ],
    [
        "name" => "gold ring",
        "clientid" => "3063",
        "weight" => "100",
        "slottype" => "ring",
    ],
    [
        "name" => "stealth ring",
        "clientid" => "3086",
        "weight" => "100",
        "slottype" => "ring",
        "duration" => "600",
        "invisible" => "true",
    ],
    [
        "name" => "power ring",
        "clientid" => "3087",
        "weight" => "80",
        "slottype" => "ring",
        "duration" => "1800",
        "skillfist" => "6",
    ],
    [
        "name" => "energy ring",
        "clientid" => "3088",
        "weight" => "80",
        "slottype" => "ring",
        "duration" => "600",
        "manashield" => "1",
    ],
    [
        "name" => "life ring",
        "clientid" => "3089",
        "weight" => "80",
        "slottype" => "ring",
        "duration" => "1200",
        "healthgain" => "1",
        "healthticks" => "3000",
        "managain" => "1",
        "manaticks" => "3000",
    ],
    [
        "name" => "time ring",
        "clientid" => "3090",
        "weight" => "90",
        "slottype" => "ring",
        "duration" => "600",
    ],
    [
        "name" => "sword ring",
        "clientid" => "3091",
        "weight" => "90",
        "slottype" => "ring",
    ],
    [
        "name" => "axe ring",
        "clientid" => "3092",
        "weight" => "90",
        "slottype" => "ring",
    ],
    [
        "name" => "club ring",
        "clientid" => "3093",
        "weight" => "90",
        "slottype" => "ring",
    ],
    [
        "name" => "sword ring",
        "clientid" => "3094",
        "weight" => "90",
        "slottype" => "ring",
        "duration" => "1800",
        "skillsword" => "4",
    ],
    [
        "name" => "axe ring",
        "clientid" => "3095",
        "weight" => "90",
        "slottype" => "ring",
        "duration" => "1800",
        "skillaxe" => "4",
    ],
    [
        "name" => "club ring",
        "clientid" => "3096",
        "weight" => "90",
        "slottype" => "ring",
        "duration" => "1800",
        "skillclub" => "4",
    ],
    [
        "name" => "dwarven ring",
        "clientid" => "3097",
        "weight" => "110",
        "slottype" => "ring",
    ],
    [
        "name" => "ring of healing",
        "clientid" => "3098",
        "weight" => "80",
        "slottype" => "ring",
    ],
    [
        "name" => "dwarven ring",
        "clientid" => "3099",
        "weight" => "110",
        "slottype" => "ring",
        "duration" => "3600",
        "suppressdrunk" => "true",
    ],
    [
        "name" => "ring of healing",
        "clientid" => "3100",
        "weight" => "80",
        "slottype" => "ring",
        "duration" => "450",
        "healthgain" => "1",
        "healthticks" => "1000",
        "managain" => "1",
        "manaticks" => "1000",
    ],
    [
        "name" => "ring of wishes",
        "clientid" => "3245",
        "weight" => "50",
        "slottype" => "ring",
    ],
];

$containers = [
    [
        "name" => "bag",
        "clientid" => "2853",
        "weight" => "800",
        "slottype" => "backpack",
        "containersize" => "8",
    ],
    [
        "name" => "backpack",
        "clientid" => "2854",
        "weight" => "1800",
        "slottype" => "backpack",
        "containersize" => "20",
    ],
    [
        "name" => "bag",
        "clientid" => "2857",
        "weight" => "800",
        "slottype" => "backpack",
        "containersize" => "8",
    ],
    [
        "name" => "bag",
        "clientid" => "2858",
        "weight" => "800",
        "slottype" => "backpack",
        "containersize" => "8",
    ],
    [
        "name" => "bag",
        "clientid" => "2859",
        "weight" => "800",
        "slottype" => "backpack",
        "containersize" => "8",
    ],
    [
        "name" => "bag",
        "clientid" => "2860",
        "weight" => "800",
        "slottype" => "backpack",
        "containersize" => "8",
    ],
    [
        "name" => "bag",
        "clientid" => "2861",
        "weight" => "800",
        "slottype" => "backpack",
        "containersize" => "8",
    ],
    [
        "name" => "bag",
        "clientid" => "2862",
        "weight" => "800",
        "slottype" => "backpack",
        "containersize" => "8",
    ],
    [
        "name" => "bag",
        "clientid" => "2863",
        "weight" => "800",
        "slottype" => "backpack",
        "containersize" => "8",
    ],
    [
        "name" => "backpack",
        "clientid" => "2865",
        "weight" => "1800",
        "slottype" => "backpack",
        "containersize" => "20",
    ],
    [
        "name" => "backpack",
        "clientid" => "2866",
        "weight" => "1800",
        "slottype" => "backpack",
        "containersize" => "20",
    ],
    [
        "name" => "backpack",
        "clientid" => "2867",
        "weight" => "1800",
        "slottype" => "backpack",
        "containersize" => "20",
    ],
    [
        "name" => "backpack",
        "clientid" => "2868",
        "weight" => "1800",
        "slottype" => "backpack",
        "containersize" => "20",
    ],
    [
        "name" => "backpack",
        "clientid" => "2869",
        "weight" => "1800",
        "slottype" => "backpack",
        "containersize" => "20",
    ],
    [
        "name" => "backpack",
        "clientid" => "2870",
        "weight" => "1800",
        "slottype" => "backpack",
        "containersize" => "20",
    ],
    [
        "name" => "backpack",
        "clientid" => "2871",
        "weight" => "1800",
        "slottype" => "backpack",
        "containersize" => "20",
    ],
    [
        "name" => "letterbag",
        "clientid" => "3217",
        "weight" => "50000",
        "slottype" => "backpack",
    ],
    [
        "name" => "bag",
        "clientid" => "2864",
        "weight" => "800",
        "slottype" => "backpack",
        "containersize" => "8",
    ],
    [
        "name" => "backpack",
        "clientid" => "2872",
        "weight" => "1800",
        "slottype" => "backpack",
        "containersize" => "20",
    ],
    [
        "name" => "old and used backpack",
        "clientid" => "3244",
        "weight" => "1800",
        "slottype" => "backpack",
        "containersize" => "20",
    ],
    [
        "name" => "ravenor backpack",
        "clientid" => "5103",
        "weight" => "1800",
        "slottype" => "backpack",
        "containersize" => "60",
    ],
    [
        "name" => "ravenor backpack",
        "clientid" => "5114",
        "weight" => "1800",
        "slottype" => "backpack",
        "containersize" => "40",
    ],
	[
        "name" => "ravenor reduction backpack",
        "clientid" => "5766",
        "weight" => "1800",
        "slottype" => "backpack",
        "containersize" => "40",
    ],
    [
        "name" => "pumpkin backpack",
        "clientid" => "5194",
        "weight" => "1800",
        "slottype" => "backpack",
        "containersize" => "20",
    ],
    [
        "name" => "halloween backpack",
        "clientid" => "5205",
        "weight" => "1800",
        "slottype" => "backpack",
        "containersize" => "24",
    ],
    [
        "name" => "christmas backpack",
        "clientid" => "5212",
        "weight" => "1800",
        "slottype" => "backpack",
        "containersize" => "24",
    ],
    [
        "name" => "christmas backpack",
        "clientid" => "5213",
        "weight" => "1800",
        "slottype" => "backpack",
        "containersize" => "24",
    ],
    [
        "name" => "grinch backpack",
        "clientid" => "5214",
        "weight" => "1800",
        "slottype" => "backpack",
        "containersize" => "24",
    ],
    [
        "name" => "grinch backpack",
        "clientid" => "5215",
        "weight" => "1800",
        "slottype" => "backpack",
        "containersize" => "24",
    ],
    [
        "name" => "grinch backpack",
        "clientid" => "5216",
        "weight" => "1800",
        "slottype" => "backpack",
        "containersize" => "24",
    ],
    [
        "name" => "grinch backpack",
        "clientid" => "5217",
        "weight" => "1800",
        "slottype" => "backpack",
        "containersize" => "24",
    ],
    [
        "name" => "backpack",
        "clientid" => "5124",
        "weight" => "1800",
        "slottype" => "backpack",
        "containersize" => "20",
    ],
    [
        "name" => "backpack",
        "clientid" => "5125",
        "weight" => "1800",
        "slottype" => "backpack",
        "containersize" => "20",
    ],
    [
        "name" => "backpack",
        "clientid" => "5126",
        "weight" => "1800",
        "slottype" => "backpack",
        "containersize" => "20",
    ],
    [
        "name" => "backpack",
        "clientid" => "5127",
        "weight" => "1800",
        "slottype" => "backpack",
        "containersize" => "20",
    ],
    [
        "name" => "backpack",
        "clientid" => "5128",
        "weight" => "1800",
        "slottype" => "backpack",
        "containersize" => "20",
    ],
    [
        "name" => "backpack",
        "clientid" => "5129",
        "weight" => "1800",
        "slottype" => "backpack",
        "containersize" => "20",
    ],
    [
        "name" => "backpack",
        "clientid" => "5130",
        "weight" => "1800",
        "slottype" => "backpack",
        "containersize" => "20",
    ],
    [
        "name" => "backpack",
        "clientid" => "5131",
        "weight" => "1800",
        "slottype" => "backpack",
        "containersize" => "20",
    ],
    [
        "name" => "backpack",
        "clientid" => "5132",
        "weight" => "1800",
        "slottype" => "backpack",
        "containersize" => "20",
    ],
    [
        "name" => "backpack",
        "clientid" => "5133",
        "weight" => "1800",
        "slottype" => "backpack",
        "containersize" => "20",
    ],
    [
        "name" => "backpack",
        "clientid" => "5134",
        "weight" => "1800",
        "slottype" => "backpack",
        "containersize" => "20",
    ],
    [
        "name" => "gold pouch",
        "clientid" => "5123",
        "weight" => "1800",
        "slottype" => "backpack",
        "containersize" => "100",
    ],
];

$shield = [
    [
        "name" => "steel shield",
        "clientid" => "3409",
        "weight" => "6900",
        "defense" => "21",
    ],
    [
        "name" => "plate shield",
        "clientid" => "3410",
        "weight" => "6500",
        "defense" => "17",
    ],
    [
        "name" => "brass shield",
        "clientid" => "3411",
        "weight" => "6000",
        "defense" => "16",
    ],
    [
        "name" => "wooden shield",
        "clientid" => "3412",
        "weight" => "4000",
        "defense" => "14",
    ],
    [
        "name" => "battle shield",
        "clientid" => "3413",
        "weight" => "6200",
        "defense" => "23",
    ],
    [
        "name" => "mastermind shield",
        "clientid" => "3414",
        "weight" => "5700",
        "defense" => "37",
    ],
    [
        "name" => "guardian shield",
        "clientid" => "3415",
        "weight" => "5500",
        "defense" => "30",
    ],
    [
        "name" => "dragon shield",
        "clientid" => "3416",
        "weight" => "6000",
        "defense" => "31",
    ],
    [
        "name" => "shield of honour",
        "clientid" => "3417",
        "weight" => "5400",
        "defense" => "33",
    ],
    [
        "name" => "beholder shield",
        "clientid" => "3418",
        "weight" => "4700",
        "defense" => "28",
    ],
    [
        "name" => "crown shield",
        "clientid" => "3419",
        "weight" => "6200",
        "defense" => "32",
    ],
    [
        "name" => "demon shield",
        "clientid" => "3420",
        "weight" => "2600",
        "defense" => "35",
    ],
    [
        "name" => "dark shield",
        "clientid" => "3421",
        "weight" => "5200",
        "defense" => "25",
    ],
    [
        "name" => "great shield",
        "clientid" => "3422",
        "weight" => "8400",
        "defense" => "38",
    ],
    [
        "name" => "blessed shield",
        "clientid" => "3423",
        "weight" => "6800",
        "defense" => "40",
    ],
    [
        "name" => "ornamented shield",
        "clientid" => "3424",
        "weight" => "6700",
        "defense" => "22",
    ],
    [
        "name" => "dwarven shield",
        "clientid" => "3425",
        "weight" => "5500",
        "defense" => "26",
    ],
    [
        "name" => "studded shield",
        "clientid" => "3426",
        "weight" => "5800",
        "defense" => "15",
    ],
	[
        "name" => "ravenor shield",
        "clientid" => "5719",
        "weight" => "5500",
        "defense" => "30",
    ],
    [
        "name" => "rose shield",
        "clientid" => "3427",
        "weight" => "5200",
        "defense" => "27",
    ],
    [
        "name" => "tower shield",
        "clientid" => "3428",
        "weight" => "8200",
        "defense" => "32",
    ],
    [
        "name" => "black shield",
        "clientid" => "3429",
        "weight" => "4200",
        "defense" => "18",
    ],
    [
        "name" => "copper shield",
        "clientid" => "3430",
        "weight" => "6300",
        "defense" => "19",
    ],
    [
        "name" => "viking shield",
        "clientid" => "3431",
        "weight" => "6600",
        "defense" => "22",
    ],
    [
        "name" => "ancient shield",
        "clientid" => "3432",
        "weight" => "6100",
        "defense" => "27",
    ],
    [
        "name" => "griffin shield",
        "clientid" => "3433",
        "weight" => "5000",
        "defense" => "29",
    ],
    [
        "name" => "vampire shield",
        "clientid" => "3434",
        "weight" => "3800",
        "defense" => "34",
    ],
    [
        "name" => "castle shield",
        "clientid" => "3435",
        "weight" => "4900",
        "defense" => "28",
    ],
    [
        "name" => "medusa shield",
        "clientid" => "3436",
        "weight" => "5800",
        "defense" => "33",
    ],
    [
        "name" => "amazon shield",
        "clientid" => "3437",
        "weight" => "6200",
        "defense" => "32",
    ],
    [
        "name" => "eagle shield",
        "clientid" => "3438",
        "weight" => "6200",
        "defense" => "32",
    ],
    [
        "name" => "phoenix shield",
        "clientid" => "3439",
        "weight" => "3500",
        "defense" => "34",
    ],
    [
        "name" => "scarab shield",
        "clientid" => "3440",
        "weight" => "4700",
        "defense" => "25",
    ],
    [
        "name" => "bone shield",
        "clientid" => "3441",
        "weight" => "5500",
        "defense" => "20",
    ],
    [
        "name" => "tempest shield",
        "clientid" => "3442",
        "weight" => "5100",
        "defense" => "36",
        "raritytier" => "3",
    ],
    [
        "name" => "tusk shield",
        "clientid" => "3443",
        "weight" => "6900",
        "defense" => "27",
    ],
    [
        "name" => "sentinel shield",
        "clientid" => "3444",
        "weight" => "4900",
        "defense" => "22",
    ],
    [
        "name" => "salamander shield",
        "clientid" => "3445",
        "weight" => "5900",
        "defense" => "26",
    ],
];

$axes = [
    [
        "name" => "battle axe",
        "clientid" => "3266",
        "weight" => "5000",
        "defense" => "8",
        "attack" => "31",
        "attackspeed" => "2500",
        "slottype" => "two-handed",
    ],
    [
        "name" => "hand axe",
        "clientid" => "3268",
        "weight" => "1800",
        "defense" => "5",
        "attack" => "10",
        "attackspeed" => "2000",
    ],
    [
        "name" => "halberd",
        "clientid" => "3269",
        "weight" => "9000",
        "defense" => "11",
        "attack" => "44",
        "attackspeed" => "2500",
        "slottype" => "two-handed",
    ],
    [
        "name" => "axe",
        "clientid" => "3274",
        "weight" => "4000",
        "defense" => "6",
        "attack" => "12",
        "attackspeed" => "2000",
    ],
    [
        "name" => "double axe",
        "clientid" => "3275",
        "weight" => "7000",
        "defense" => "9",
        "attack" => "44",
        "attackspeed" => "2500",
        "slottype" => "two-handed",
    ],
    [
        "name" => "hatchet",
        "clientid" => "3276",
        "weight" => "3500",
        "defense" => "8",
        "attack" => "15",
        "attackspeed" => "2000",
    ],
    [
        "name" => "sickle",
        "clientid" => "3293",
        "weight" => "1050",
        "defense" => "4",
        "attack" => "7",
        "attackspeed" => "2000",
    ],
    [
        "name" => "dragon lance",
        "clientid" => "3302",
        "weight" => "6700",
        "defense" => "12",
        "attack" => "59",
        "attackspeed" => "2500",
        "slottype" => "two-handed",
    ],
    [
        "name" => "great axe",
        "clientid" => "3303",
        "weight" => "9000",
        "defense" => "17",
        "attack" => "65",
        "attackspeed" => "2500",
        "slottype" => "two-handed",
    ],
    [
        "name" => "golden sickle",
        "clientid" => "3306",
        "weight" => "1950",
        "defense" => "6",
        "attack" => "13",
        "attackspeed" => "2000",
    ],
    [
        "name" => "obsidian lance",
        "clientid" => "3313",
        "weight" => "8000",
        "defense" => "8",
        "attack" => "43",
        "attackspeed" => "2500",
        "slottype" => "two-handed",
    ],
    [
        "name" => "naginata",
        "clientid" => "3314",
        "weight" => "7800",
        "defense" => "19",
        "attack" => "49",
        "attackspeed" => "2500",
        "slottype" => "two-handed",
    ],
    [
        "name" => "guardian halberd",
        "clientid" => "3315",
        "weight" => "11000",
        "defense" => "11",
        "attack" => "58",
        "attackspeed" => "2500",
        "slottype" => "two-handed",
    ],
    [
        "name" => "orcish axe",
        "clientid" => "3316",
        "weight" => "4500",
        "defense" => "12",
        "attack" => "23",
        "attackspeed" => "2000",
    ],
    [
        "name" => "barbarian axe",
        "clientid" => "3317",
        "weight" => "5100",
        "defense" => "18",
        "attack" => "28",
        "attackspeed" => "2000",
    ],
    [
        "name" => "knight axe",
        "clientid" => "3318",
        "weight" => "5900",
        "defense" => "21",
        "attack" => "33",
        "attackspeed" => "2000",
    ],
    [
        "name" => "stonecutter axe",
        "clientid" => "3319",
        "weight" => "9900",
        "defense" => "30",
        "attack" => "50",
        "skillaxe" => "4",
        "attackspeed" => "2000",
    ],
    [
        "name" => "fire axe",
        "clientid" => "3320",
        "weight" => "4000",
        "defense" => "16",
        "attack" => "38",
        "attackspeed" => "2000",
        "lightlevel" => "3",
    ],
    [
        "name" => "dwarven axe",
        "clientid" => "3323",
        "weight" => "8200",
        "defense" => "19",
        "attack" => "31",
        "attackspeed" => "2000",
    ],
    [
        "name" => "daramanian waraxe",
        "clientid" => "3328",
        "weight" => "5250",
        "defense" => "11",
        "attack" => "49",
        "attackspeed" => "2500",
        "slottype" => "two-handed",
    ],
    [
        "name" => "daramanian axe",
        "clientid" => "3329",
        "weight" => "4100",
        "defense" => "8",
        "attack" => "16",
        "attackspeed" => "2000",
    ],
    [
        "name" => "ravager's axe",
        "clientid" => "3331",
        "weight" => "5250",
        "defense" => "11",
        "attack" => "61",
        "attackspeed" => "2500",
        "slottype" => "two-handed",
    ],
    [
        "name" => "twin axe",
        "clientid" => "3335",
        "weight" => "6400",
        "defense" => "18",
        "attack" => "56",
        "attackspeed" => "2600",
        "slottype" => "two-handed",
    ],
    [
        "name" => "war axe",
        "clientid" => "3342",
        "weight" => "6150",
        "defense" => "8",
        "attack" => "60",
        "attackspeed" => "2500",
        "slottype" => "two-handed",
    ],
    [
        "name" => "beastslayer axe",
        "clientid" => "3344",
        "weight" => "6150",
        "defense" => "12",
        "attack" => "35",
        "attackspeed" => "2000",
    ],
    [
        "name" => "ripper lance",
        "clientid" => "3346",
        "weight" => "8000",
        "defense" => "5",
        "attack" => "35",
        "attackspeed" => "2500",
        "slottype" => "two-handed",
    ],
    [
        "name" => "hunting spear",
        "clientid" => "3347",
        "weight" => "8000",
        "defense" => "6",
        "attack" => "23",
        "attackspeed" => "2500",
        "slottype" => "two-handed",
    ],
];

$clubs = [
    [
        "name" => "giant smithhammer",
        "clientid" => "3208",
        "weight" => "6800",
        "defense" => "14",
        "attack" => "24",
        "attackspeed" => "2000",
    ],
    [
        "name" => "club",
        "clientid" => "3270",
        "weight" => "2500",
        "defense" => "7",
        "attack" => "7",
        "attackspeed" => "2000",
    ],
    [
        "name" => "war hammer",
        "clientid" => "3279",
        "weight" => "8500",
        "defense" => "8",
        "attack" => "56",
        "attackspeed" => "2500",
        "slottype" => "two-handed",
    ],
    [
        "name" => "morning star",
        "clientid" => "3282",
        "weight" => "5400",
        "defense" => "11",
        "attack" => "25",
        "attackspeed" => "2000",
    ],
    [
        "name" => "mace",
        "clientid" => "3286",
        "weight" => "3800",
        "defense" => "11",
        "attack" => "16",
        "attackspeed" => "2000",
    ],
    [
        "name" => "staff",
        "clientid" => "3289",
        "weight" => "3800",
        "defense" => "25",
        "attack" => "10",
        "slottype" => "two-handed",
    ],
    [
        "name" => "crowbar",
        "clientid" => "3304",
        "weight" => "2100",
        "defense" => "6",
        "attack" => "6",
        "attackspeed" => "2000",
    ],
    [
        "name" => "battle hammer",
        "clientid" => "3305",
        "weight" => "6800",
        "defense" => "14",
        "attack" => "24",
        "attackspeed" => "2000",
    ],
    [
        "name" => "thunder hammer",
        "clientid" => "3309",
        "weight" => "12500",
        "defense" => "35",
        "attack" => "49",
        "skillclub" => "4",
        "attackspeed" => "2000",
    ],
    [
        "name" => "iron hammer",
        "clientid" => "3310",
        "weight" => "6600",
        "defense" => "10",
        "attack" => "18",
        "attackspeed" => "2000",
    ],
    [
        "name" => "clerical mace",
        "clientid" => "3311",
        "weight" => "5800",
        "defense" => "15",
        "attack" => "28",
        "attackspeed" => "2000",
    ],
    [
        "name" => "silver mace",
        "clientid" => "3312",
        "weight" => "6700",
        "defense" => "30",
        "attack" => "40",
        "attackspeed" => "2000",
    ],
    [
        "name" => "enchanted staff",
        "clientid" => "3321",
        "weight" => "3800",
        "defense" => "45",
        "attack" => "39",
        "slottype" => "two-handed",
        "duration" => "60",
    ],
    [
        "name" => "dragon hammer",
        "clientid" => "3322",
        "weight" => "9700",
        "defense" => "20",
        "attack" => "32",
        "attackspeed" => "2000",
    ],
    [
        "name" => "skull staff",
        "clientid" => "3324",
        "weight" => "1700",
        "defense" => "12",
        "attack" => "36",
        "attackspeed" => "2000",
        "lightlevel" => "2",
    ],
    [
        "name" => "light mace",
        "clientid" => "3325",
        "weight" => "4100",
        "defense" => "9",
        "attack" => "14",
        "attackspeed" => "2000",
    ],
    [
        "name" => "daramanian mace",
        "clientid" => "3327",
        "weight" => "6800",
        "defense" => "12",
        "attack" => "21",
        "attackspeed" => "2000",
    ],
    [
        "name" => "hammer of wrath",
        "clientid" => "3332",
        "weight" => "7000",
        "defense" => "9",
        "attack" => "60",
        "attackspeed" => "2500",
        "slottype" => "two-handed",
    ],
    [
        "name" => "crystal mace",
        "clientid" => "3333",
        "weight" => "8000",
        "defense" => "16",
        "attack" => "38",
        "attackspeed" => "2000",
    ],
    [
        "name" => "studded club",
        "clientid" => "3336",
        "weight" => "3500",
        "defense" => "8",
        "attack" => "9",
        "attackspeed" => "2000",
    ],
    [
        "name" => "bone club",
        "clientid" => "3337",
        "weight" => "3900",
        "defense" => "8",
        "attack" => "12",
        "attackspeed" => "2000",
    ],
    [
        "name" => "heavy mace",
        "clientid" => "3340",
        "weight" => "11000",
        "defense" => "23",
        "attack" => "63",
        "attackspeed" => "2500",
        "slottype" => "two-handed",
    ],
    [
        "name" => "scythe",
        "clientid" => "3453",
        "weight" => "3000",
        "defense" => "3",
        "attack" => "8",
        "slottype" => "two-handed",
    ],
    [
        "name" => "lich staff",
        "clientid" => "3343",
        "weight" => "4100",
        "defense" => "30",
        "attack" => "40",
        "attackspeed" => "2000",
    ],
    [
        "name" => "banana staff",
        "clientid" => "3348",
        "weight" => "5000",
        "defense" => "15",
        "attack" => "25",
        "attackspeed" => "2000",
    ],
];

$swords = [
    [
        "name" => "sword",
        "clientid" => "3264",
        "weight" => "3500",
        "defense" => "12",
        "attack" => "14",
        "attackspeed" => "2000",
    ],
    [
        "name" => "two handed sword",
        "clientid" => "3265",
        "weight" => "7000",
        "defense" => "19",
        "attack" => "38",
        "attackspeed" => "2500",
        "slottype" => "two-handed",
    ],
    [
        "name" => "dagger",
        "clientid" => "3267",
        "weight" => "950",
        "defense" => "6",
        "attack" => "8",
        "attackspeed" => "2000",
    ],
    [
        "name" => "spike sword",
        "clientid" => "3271",
        "weight" => "5000",
        "defense" => "21",
        "attack" => "24",
        "attackspeed" => "2000",
    ],
    [
        "name" => "rapier",
        "clientid" => "3272",
        "weight" => "1500",
        "defense" => "8",
        "attack" => "10",
        "attackspeed" => "2000",
    ],
    [
        "name" => "sabre",
        "clientid" => "3273",
        "weight" => "2500",
        "defense" => "10",
        "attack" => "12",
        "attackspeed" => "2000",
    ],
    [
        "name" => "magic longsword",
        "clientid" => "3278",
        "weight" => "4300",
        "defense" => "30",
        "attack" => "69",
        "attackspeed" => "2500",
        "slottype" => "two-handed",
    ],
    [
        "name" => "fire sword",
        "clientid" => "3280",
        "weight" => "2300",
        "defense" => "20",
        "attack" => "35",
        "attackspeed" => "2000",
        "lightlevel" => "3",
    ],
    [
        "name" => "giant sword",
        "clientid" => "3281",
        "weight" => "18000",
        "defense" => "17",
        "attack" => "58",
        "attackspeed" => "2500",
        "slottype" => "two-handed",
    ],
    [
        "name" => "carlin sword",
        "clientid" => "3283",
        "weight" => "4000",
        "defense" => "13",
        "attack" => "15",
        "attackspeed" => "2000",
    ],
    [
        "name" => "ice rapier",
        "clientid" => "3284",
        "weight" => "1500",
        "defense" => "1",
        "attack" => "100",
        "attackspeed" => "2000",
        "charges" => "1",
    ],
    [
        "name" => "longsword",
        "clientid" => "3285",
        "weight" => "4200",
        "defense" => "14",
        "attack" => "17",
        "attackspeed" => "2000",
    ],
    [
        "name" => "magic sword",
        "clientid" => "3288",
        "weight" => "4200",
        "defense" => "35",
        "attack" => "48",
        "skillsword" => "4",
        "attackspeed" => "2000",
    ],
    [
        "name" => "silver dagger",
        "clientid" => "3290",
        "weight" => "1020",
        "defense" => "7",
        "attack" => "8",
        "attackspeed" => "2000",
    ],
    [
        "name" => "knife",
        "clientid" => "3291",
        "weight" => "420",
        "defense" => "5",
        "attack" => "7",
        "attackspeed" => "2000",
    ],
    [
        "name" => "combat knife",
        "clientid" => "3292",
        "weight" => "870",
        "defense" => "6",
        "attack" => "8",
        "attackspeed" => "2000",
    ],
    [
        "name" => "short sword",
        "clientid" => "3294",
        "weight" => "3500",
        "defense" => "11",
        "attack" => "11",
        "attackspeed" => "2000",
    ],
    [
        "name" => "bright sword",
        "clientid" => "3295",
        "weight" => "2900",
        "defense" => "30",
        "attack" => "36",
        "attackspeed" => "2000",
        "lightlevel" => "2",
    ],
    [
        "name" => "warlord sword",
        "clientid" => "3296",
        "weight" => "6400",
        "defense" => "29",
        "attack" => "66",
        "attackspeed" => "2500",
        "slottype" => "two-handed",
    ],
    [
        "name" => "serpent sword",
        "clientid" => "3297",
        "weight" => "4100",
        "defense" => "15",
        "attack" => "26",
        "attackspeed" => "2000",
    ],
    [
        "name" => "poison dagger",
        "clientid" => "3299",
        "weight" => "880",
        "defense" => "8",
        "attack" => "18",
        "attackspeed" => "2000",
    ],
    [
        "name" => "katana",
        "clientid" => "3300",
        "weight" => "3100",
        "defense" => "12",
        "attack" => "16",
        "attackspeed" => "2000",
    ],
    [
        "name" => "broadsword",
        "clientid" => "3301",
        "weight" => "5250",
        "defense" => "17",
        "attack" => "33",
        "attackspeed" => "2500",
        "slottype" => "two-handed",
    ],
    [
        "name" => "scimitar",
        "clientid" => "3307",
        "weight" => "2900",
        "defense" => "13",
        "attack" => "19",
        "attackspeed" => "2000",
    ],
    [
        "name" => "machete",
        "clientid" => "3308",
        "weight" => "1650",
        "defense" => "9",
        "attack" => "12",
        "attackspeed" => "2000",
    ],
    [
        "name" => "foil",
        "clientid" => "3326",
        "weight" => "1450",
        "defense" => "11",
        "attack" => "9",
    ],
    [
        "name" => "heavy machete",
        "clientid" => "3330",
        "weight" => "1840",
        "defense" => "10",
        "attack" => "16",
        "attackspeed" => "2000",
    ],
    [
        "name" => "pharaoh sword",
        "clientid" => "3334",
        "weight" => "15000",
        "defense" => "23",
        "attack" => "41",
        "attackspeed" => "2000",
    ],
    [
        "name" => "bone sword",
        "clientid" => "3338",
        "weight" => "1900",
        "defense" => "10",
        "attack" => "14",
        "attackspeed" => "2000",
    ],
    [
        "name" => "djinn blade",
        "clientid" => "3339",
        "weight" => "2450",
        "defense" => "22",
        "attack" => "38",
        "attackspeed" => "2000",
    ],
    [
        "name" => "templar scytheblade",
        "clientid" => "3345",
        "weight" => "2900",
        "defense" => "15",
        "attack" => "23",
    ],
];

$ammunition = [
    [
        "name" => "bolt",
        "clientid" => "3446",
        "weight" => "80",
        "attack" => "30",
        "ammotype" => "bolt",
    ],
    [
        "name" => "arrow",
        "clientid" => "3447",
        "weight" => "70",
        "attack" => "25",
        "ammotype" => "arrow",
    ],
    [
        "name" => "poison arrow",
        "clientid" => "3448",
        "weight" => "80",
        "attack" => "10",
        "ammotype" => "arrow",
    ],
    [
        "name" => "burst arrow",
        "clientid" => "3449",
        "weight" => "90",
        "ammotype" => "arrow",
    ],
    [
        "name" => "power bolt",
        "clientid" => "3450",
        "weight" => "90",
        "attack" => "40",
        "ammotype" => "bolt",
    ],
    [
        "name" => "hunting bolt",
        "clientid" => "5628",
        "weight" => "90",
        "attack" => "34",
        "ammotype" => "bolt",
    ],
    [
        "name" => "hunting arrow",
        "clientid" => "5616",
        "weight" => "80",
        "attack" => "32",
        "ammotype" => "arrow",
    ],
];

$wands = [
    [
        "name" => "wooden wand",
        "clientid" => "3065",
        "weight" => "2650",
        "raritytier" => "1",
    ],
    [
        "name" => "golden wand",
        "clientid" => "3066",
        "weight" => "4300",
        "raritytier" => "1",
        "lightlevel" => "3",
    ],
    [
        "name" => "elven wand",
        "clientid" => "3067",
        "weight" => "2100",
        "raritytier" => "2",
        "lightlevel" => "3",
    ],
    [
        "name" => "crystal wand",
        "clientid" => "3068",
        "weight" => "2800",
        "raritytier" => "4",
        "lightlevel" => "5",
    ],
    [
        "name" => "wand of might",
        "clientid" => "3069",
        "weight" => "2900",
        "raritytier" => "3",
        "lightlevel" => "4",
    ],
    [
        "name" => "conjurer wand",
        "clientid" => "3070",
        "weight" => "1950",
        "raritytier" => "2",
        "lightlevel" => "3",
    ],
    [
        "name" => "ritual wand",
        "clientid" => "3071",
        "weight" => "3050",
        "raritytier" => "3",
        "lightlevel" => "4",
    ],
    [
        "name" => "arcane wand",
        "clientid" => "3341",
        "weight" => "4000",
        "raritytier" => "4",
        "lightlevel" => "6",
    ],
];

$runes = [
    [
        "name" => "spell rune",
        "clientid" => "3148",
        "weight" => "120",
        "runespellname" => "adito grav",
    ],
    [
        "name" => "spell rune",
        "clientid" => "3149",
        "weight" => "120",
        "runespellname" => "adevo mas vis",
    ],
    [
        "name" => "spell rune",
        "clientid" => "3152",
        "weight" => "120",
        "runespellname" => "adura gran",
    ],
    [
        "name" => "spell rune",
        "clientid" => "3153",
        "weight" => "120",
        "runespellname" => "adana pox",
    ],
    [
        "name" => "spell rune",
        "clientid" => "3155",
        "weight" => "120",
        "runespellname" => "adori vita vis",
    ],
    [
        "name" => "spell rune",
        "clientid" => "3156",
        "weight" => "120",
        "runespellname" => "adevo grav vita",
        "lightlevel" => "1",
    ],
    [
        "name" => "spell rune",
        "clientid" => "3158",
        "weight" => "120",
        "lightlevel" => "1",
    ],
    [
        "name" => "spell rune",
        "clientid" => "3160",
        "weight" => "120",
        "runespellname" => "adura vita",
        "lightlevel" => "1",
    ],
    [
        "name" => "spell rune",
        "clientid" => "3161",
        "weight" => "120",
        "lightlevel" => "1",
    ],
    [
        "name" => "spell rune",
        "clientid" => "3164",
        "weight" => "120",
        "runespellname" => "adevo grav vis",
        "lightlevel" => "1",
    ],
    [
        "name" => "spell rune",
        "clientid" => "3165",
        "weight" => "120",
        "runespellname" => "adana ani",
        "lightlevel" => "1",
    ],
    [
        "name" => "spell rune",
        "clientid" => "3166",
        "weight" => "120",
        "runespellname" => "adevo mas grav vis",
        "lightlevel" => "1",
    ],
    [
        "name" => "spell rune",
        "clientid" => "3172",
        "weight" => "120",
        "runespellname" => "adevo grav pox",
    ],
    [
        "name" => "spell rune",
        "clientid" => "3173",
        "weight" => "120",
        "runespellname" => "adevo mas pox",
    ],
    [
        "name" => "spell rune",
        "clientid" => "3174",
        "weight" => "120",
        "runespellname" => "adori",
    ],
    [
        "name" => "spell rune",
        "clientid" => "3175",
        "weight" => "120",
    ],
    [
        "name" => "spell rune",
        "clientid" => "3176",
        "weight" => "120",
        "runespellname" => "adevo mas grav pox",
    ],
    [
        "name" => "spell rune",
        "clientid" => "3177",
        "weight" => "120",
        "runespellname" => "adeta sio",
    ],
    [
        "name" => "spell rune",
        "clientid" => "3178",
        "weight" => "120",
        "runespellname" => "adevo ina",
    ],
    [
        "name" => "spell rune",
        "clientid" => "3179",
        "weight" => "120",
        "runespellname" => "adevo res pox",
    ],
    [
        "name" => "spell rune",
        "clientid" => "3180",
        "weight" => "120",
        "runespellname" => "adevo grav tera",
        "lightlevel" => "2",
    ],
    [
        "name" => "spell rune",
        "clientid" => "3182",
        "weight" => "120",
        "lightlevel" => "2",
    ],
    [
        "name" => "spell rune",
        "clientid" => "3188",
        "weight" => "120",
        "runespellname" => "adevo grav flam",
        "lightlevel" => "1",
    ],
    [
        "name" => "spell rune",
        "clientid" => "3189",
        "weight" => "120",
        "runespellname" => "adori flam",
        "lightlevel" => "1",
    ],
    [
        "name" => "spell rune",
        "clientid" => "3190",
        "weight" => "120",
        "runespellname" => "adevo mas grav flam",
        "lightlevel" => "1",
    ],
    [
        "name" => "spell rune",
        "clientid" => "3191",
        "weight" => "120",
        "runespellname" => "adori gran flam",
        "lightlevel" => "1",
    ],
    [
        "name" => "spell rune",
        "clientid" => "3192",
        "weight" => "120",
        "runespellname" => "adevo mas flam",
        "lightlevel" => "1",
    ],
    [
        "name" => "spell rune",
        "clientid" => "3195",
        "weight" => "120",
        "runespellname" => "adevo res flam",
        "lightlevel" => "1",
    ],
    [
        "name" => "spell rune",
        "clientid" => "3197",
        "weight" => "120",
        "runespellname" => "adito tera",
        "lightlevel" => "1",
    ],
    [
        "name" => "spell rune",
        "clientid" => "3198",
        "weight" => "120",
        "runespellname" => "adori gran",
        "lightlevel" => "1",
    ],
    [
        "name" => "spell rune",
        "clientid" => "3200",
        "weight" => "120",
        "runespellname" => "adevo mas hur",
        "lightlevel" => "1",
    ],
    [
        "name" => "spell rune",
        "clientid" => "3202",
        "weight" => "120",
        "lightlevel" => "1",
    ],
    [
        "name" => "spell rune",
        "clientid" => "3203",
        "weight" => "120",
        "runespellname" => "adana mort",
        "lightlevel" => "1",
    ],
];

$distance = [
    [
        "name" => "small stone",
        "clientid" => "1781",
        "weight" => "180",
        "attack" => "7",
        "attackspeed" => "2000",
        "range" => "7",
    ],
    [
        "name" => "snowball",
        "clientid" => "2992",
        "weight" => "80",
        "attackspeed" => "2000",
        "range" => "7",
    ],
    [
        "name" => "spear",
        "clientid" => "3277",
        "weight" => "2000",
        "attack" => "30",
        "attackspeed" => "2000",
        "range" => "7",
    ],
    [
        "name" => "throwing star",
        "clientid" => "3287",
        "weight" => "100",
        "attack" => "25",
        "attackspeed" => "2000",
        "range" => "7",
    ],
    [
        "name" => "throwing knife",
        "clientid" => "3298",
        "weight" => "210",
        "attack" => "30",
        "attackspeed" => "2000",
        "range" => "7",
    ],
    [
        "name" => "crossbow",
        "clientid" => "3349",
        "weight" => "4000",
        "range" => "7",
        "slottype" => "two-handed",
        "ammotype" => "bolt",
        "raritytier" => "1",
    ],
    [
        "name" => "bow",
        "clientid" => "3350",
        "weight" => "3100",
        "attackspeed" => "2000",
        "range" => "7",
        "slottype" => "two-handed",
        "ammotype" => "arrow",
        "raritytier" => "1",
    ],
    [
        "name" => "modified crossbow",
        "clientid" => "5613",
        "weight" => "3400",
        "range" => "7",
        "slottype" => "two-handed",
        "ammotype" => "bolt",
        "raritytier" => "2",
    ],
    [
        "name" => "ancient crossbow",
        "clientid" => "5615",
        "weight" => "3000",
        "range" => "7",
        "slottype" => "two-handed",
        "ammotype" => "bolt",
        "raritytier" => "3",
    ],
    [
        "name" => "sacred crossbow",
        "clientid" => "5627",
        "weight" => "4400",
        "range" => "7",
        "slottype" => "two-handed",
        "ammotype" => "bolt",
        "raritytier" => "4",
    ],
    [
        "name" => "modified bow",
        "clientid" => "5625",
        "weight" => "2600",
        "attackspeed" => "2000",
        "range" => "7",
        "slottype" => "two-handed",
        "ammotype" => "arrow",
        "raritytier" => "2",
    ],
    [
        "name" => "ancient bow",
        "clientid" => "5630",
        "weight" => "2100",
        "attackspeed" => "2000",
        "range" => "7",
        "slottype" => "two-handed",
        "ammotype" => "arrow",
        "raritytier" => "3",
    ],
    [
        "name" => "sacred bow",
        "clientid" => "5631",
        "weight" => "3500",
        "attackspeed" => "2000",
        "range" => "7",
        "slottype" => "two-handed",
        "ammotype" => "arrow",
        "raritytier" => "4",
    ],
    [
        "name" => "arrow quiver",
        "clientid" => "5090",
        "weight" => "1800",
        "ammotype" => "arrow",
        "containersize" => "5",
        "raritytier" => "1",
    ],
    [
        "name" => "bolt quiver",
        "clientid" => "5091",
        "weight" => "1800",
        "ammotype" => "bolt",
        "containersize" => "5",
        "raritytier" => "1",
    ],
    [
        "name" => "ravenor quiver",
        "clientid" => "5109",
        "weight" => "2200",
        "ammotype" => "arrow",
        "containersize" => "8",
    ],
    [
        "name" => "ravenor quiver",
        "clientid" => "5110",
        "weight" => "2200",
        "ammotype" => "bolt",
        "containersize" => "8",
    ],
    [
        "name" => "modified arrow quiver",
        "clientid" => "5633",
        "weight" => "2000",
        "ammotype" => "arrow",
        "containersize" => "8",
        "raritytier" => "2",
    ],
    [
        "name" => "ancient arrow quiver",
        "clientid" => "5637",
        "weight" => "2200",
        "ammotype" => "arrow",
        "containersize" => "12",
        "raritytier" => "3",
    ],
    [
        "name" => "sacred arrow quiver",
        "clientid" => "5639",
        "weight" => "2400",
        "ammotype" => "arrow",
        "containersize" => "15",
        "raritytier" => "4",
    ],
    [
        "name" => "modified bolt quiver",
        "clientid" => "5634",
        "weight" => "2000",
        "ammotype" => "bolt",
        "containersize" => "8",
        "raritytier" => "2",
    ],
    [
        "name" => "ancient bolt quiver",
        "clientid" => "5638",
        "weight" => "2200",
        "ammotype" => "bolt",
        "containersize" => "12",
        "raritytier" => "3",
    ],
    [
        "name" => "sacred bolt quiver",
        "clientid" => "5640",
        "weight" => "2400",
        "ammotype" => "bolt",
        "containersize" => "15",
        "raritytier" => "4",
    ],
];

$foods = [
    [
        "name" => "meat",
        "clientid" => "3577",
        "weight" => "1300",
    ],
    [
        "name" => "fish",
        "clientid" => "3578",
        "weight" => "520",
    ],
    [
        "name" => "salmon",
        "clientid" => "3579",
        "weight" => "320",
    ],
    [
        "name" => "fish",
        "clientid" => "3580",
        "weight" => "830",
    ],
    [
        "name" => "shrimp",
        "clientid" => "3581",
        "weight" => "50",
    ],
    [
        "name" => "ham",
        "clientid" => "3582",
        "weight" => "2000",
    ],
    [
        "name" => "dragon ham",
        "clientid" => "3583",
        "weight" => "3000",
    ],
    [
        "name" => "pear",
        "clientid" => "3584",
        "weight" => "140",
    ],
    [
        "name" => "red apple",
        "clientid" => "3585",
        "weight" => "150",
    ],
    [
        "name" => "orange",
        "clientid" => "3586",
        "weight" => "110",
    ],
    [
        "name" => "banana",
        "clientid" => "3587",
        "weight" => "180",
    ],
    [
        "name" => "blueberry",
        "clientid" => "3588",
        "weight" => "20",
    ],
    [
        "name" => "coconut",
        "clientid" => "3589",
        "weight" => "480",
    ],
    [
        "name" => "cherry",
        "clientid" => "3590",
        "weight" => "20",
    ],
    [
        "name" => "strawberry",
        "clientid" => "3591",
        "weight" => "20",
    ],
    [
        "name" => "grapes",
        "clientid" => "3592",
        "weight" => "250",
    ],
    [
        "name" => "melon",
        "clientid" => "3593",
        "weight" => "950",
    ],
    [
        "name" => "pumpkin",
        "clientid" => "3594",
        "weight" => "1350",
    ],
    [
        "name" => "carrot",
        "clientid" => "3595",
        "weight" => "160",
    ],
    [
        "name" => "tomato",
        "clientid" => "3596",
        "weight" => "100",
    ],
    [
        "name" => "corncob",
        "clientid" => "3597",
        "weight" => "350",
    ],
    [
        "name" => "cookie",
        "clientid" => "3598",
        "weight" => "10",
    ],
    [
        "name" => "candy cane",
        "clientid" => "3599",
        "weight" => "50",
    ],
    [
        "name" => "bread",
        "clientid" => "3600",
        "weight" => "500",
    ],
    [
        "name" => "roll",
        "clientid" => "3601",
        "weight" => "100",
    ],
    [
        "name" => "brown bread",
        "clientid" => "3602",
        "weight" => "400",
    ],
    [
        "name" => "bunch of wheat",
        "clientid" => "3605",
        "weight" => "1250",
    ],
    [
        "name" => "egg",
        "clientid" => "3606",
        "weight" => "30",
    ],
    [
        "name" => "cheese",
        "clientid" => "3607",
        "weight" => "400",
    ],
    [
        "name" => "white mushroom",
        "clientid" => "3723",
        "weight" => "40",
    ],
    [
        "name" => "red mushroom",
        "clientid" => "3724",
        "weight" => "50",
    ],
    [
        "name" => "brown mushroom",
        "clientid" => "3725",
        "weight" => "20",
    ],
    [
        "name" => "orange mushroom",
        "clientid" => "3726",
        "weight" => "30",
    ],
    [
        "name" => "wood mushroom",
        "clientid" => "3727",
        "weight" => "30",
    ],
    [
        "name" => "dark mushroom",
        "clientid" => "3728",
        "weight" => "10",
    ],
    [
        "name" => "fire mushroom",
        "clientid" => "3731",
        "weight" => "10",
    ],
    [
        "name" => "green mushroom",
        "clientid" => "3732",
        "weight" => "10",
    ],
];

$light = [
    [
        "name" => "lit candelabrum",
        "clientid" => "2912",
        "weight" => "5000",
        "duration" => "3000",
        "lightlevel" => "6",
    ],
    [
        "name" => "lit lamp",
        "clientid" => "2915",
        "weight" => "3000",
        "duration" => "2000",
        "lightlevel" => "6",
    ],
    [
        "name" => "lit candlestick",
        "clientid" => "2918",
        "weight" => "300",
        "duration" => "3000",
        "lightlevel" => "4",
    ],
    [
        "name" => "lit torch",
        "clientid" => "2921",
        "weight" => "500",
        "duration" => "600",
        "lightlevel" => "7",
    ],
];

$tools = [
    [
        "name" => "rope",
        "clientid" => "3003",
        "weight" => "1800",
    ],
    [
        "name" => "pitchfork",
        "clientid" => "3451",
        "weight" => "2500",
    ],
    [
        "name" => "rake",
        "clientid" => "3452",
        "weight" => "1500",
    ],
    [
        "name" => "broom",
        "clientid" => "3454",
        "weight" => "1100",
    ],
    [
        "name" => "hoe",
        "clientid" => "3455",
        "weight" => "2800",
    ],
    [
        "name" => "pick",
        "clientid" => "3456",
        "weight" => "4500",
    ],
    [
        "name" => "shovel",
        "clientid" => "3457",
        "weight" => "3500",
    ],
    [
        "name" => "wooden hammer",
        "clientid" => "3459",
        "weight" => "600",
    ],
    [
        "name" => "saw",
        "clientid" => "3461",
        "weight" => "1000",
    ],
    [
        "name" => "small axe",
        "clientid" => "3462",
        "weight" => "2000",
    ],
    [
        "name" => "closed trap",
        "clientid" => "3481",
        "weight" => "2100",
    ],
    [
        "name" => "fishing rod",
        "clientid" => "3483",
        "weight" => "850",
    ],
];

$valuables = [
    [
        "name" => "silver brooch",
        "clientid" => "3017",
        "weight" => "110",
    ],
    [
        "name" => "some golden fruits",
        "clientid" => "3020",
        "weight" => "1070",
    ],
    [
        "name" => "ancient tiara",
        "clientid" => "3022",
        "weight" => "820",
        "slottype" => "head",
        "raritytier" => "4",
    ],
    [
        "name" => "holy scarab",
        "clientid" => "3023",
        "weight" => "870",
    ],
    [
        "name" => "holy falcon",
        "clientid" => "3024",
        "weight" => "840",
    ],
    [
        "name" => "white pearl",
        "clientid" => "3026",
        "weight" => "20",
    ],
    [
        "name" => "black pearl",
        "clientid" => "3027",
        "weight" => "20",
    ],
    [
        "name" => "small diamond",
        "clientid" => "3028",
        "weight" => "10",
    ],
    [
        "name" => "small sapphire",
        "clientid" => "3029",
        "weight" => "10",
    ],
    [
        "name" => "small ruby",
        "clientid" => "3030",
        "weight" => "10",
    ],
    [
        "name" => "gold coin",
        "clientid" => "3031",
        "weight" => "10",
    ],
    [
        "name" => "small emerald",
        "clientid" => "3032",
        "weight" => "10",
    ],
    [
        "name" => "small amethyst",
        "clientid" => "3033",
        "weight" => "10",
    ],
    [
        "name" => "talon",
        "clientid" => "3034",
        "weight" => "20",
    ],
    [
        "name" => "platinum coin",
        "clientid" => "3035",
        "weight" => "10",
    ],
    [
        "name" => "violet gem",
        "clientid" => "3036",
        "weight" => "30",
    ],
    [
        "name" => "yellow gem",
        "clientid" => "3037",
        "weight" => "30",
    ],
    [
        "name" => "green gem",
        "clientid" => "3038",
        "weight" => "30",
    ],
    [
        "name" => "red gem",
        "clientid" => "3039",
        "weight" => "30",
    ],
    [
        "name" => "gold nugget",
        "clientid" => "3040",
        "weight" => "80",
    ],
    [
        "name" => "blue gem",
        "clientid" => "3041",
        "weight" => "30",
    ],
    [
        "name" => "scarab coin",
        "clientid" => "3042",
        "weight" => "20",
    ],
    [
        "name" => "crystal coin",
        "clientid" => "3043",
        "weight" => "10",
    ],
    [
        "name" => "orichalcum pearl",
        "clientid" => "5021",
        "weight" => "30",
    ],
    [
        "name" => "ravenor coin",
        "clientid" => "5097",
        "weight" => "10",
    ],
    [
        "name" => "halloween coin",
        "clientid" => "5207",
        "weight" => "0",
    ],
];

?>
