<?php

$runas = [

    "adana mort" => ["Animate Dead Rune", "Support"],
    "adana pox" => ["Cure Poison Rune", "Support"],
    "adevo mas vis" => ["Energy Bomb Rune", "Support"],
    "adori mas frigo" => ["Avalanche Rune", "Support"],
    "uteta res sac" => ["Avatar of Light", "Support"],
    "uteta res dru" => ["Avatar of Nature", "Support"],
    "uteta res eq" => ["Avatar of Steel", "Support"],
    "uteta res ven" => ["Avatar of Storm", "Support"],
    "exori" => ["Berserk", "Attack"],
    "utito tempo" => ["Blood Rage", "Support"],
    "exura infir ico" => ["Bruise Bane", "Healing"],
    "exori ico" => ["Brutal Strike", "Attack"],
    "exori infir vis" => ["Buzz", "Attack"],
    "exana ina" => ["Cancel Invisibility", "Support"],
    "exana vita" => ["Cancel Magic Shield", "Support"],
    "exeta res" => ["Challenge", "Support"],
    "adevo ina" => ["Chameleon Rune", "Support"],
    "utani tempo hur" => ["Charge", "Support"],
    "exevo infir frigo hur" => ["Chill Out", "Attack"],
    "exeta amp res" => ["Chivalrous Challenge", "Support"],
    "exevo con" => ["Conjure Arrow", "Support"],
    "exevo con flam" => ["Conjure Explosive Arrow", "Support"],
    "exevo gran mort" => ["Conjure Wand of Darkness", "Support"],
    "adeta sio" => ["Convince Creature Rune", "Support"],
    "utevo res ina" => ["Creature Illusion", "Support"],
    "exana kor" => ["Cure Bleeding", "Healing"],
    "exana flam" => ["Cure Burning", "Healing"],
    "exana mort" => ["Cure Curse", "Healing"],
    "exana vis" => ["Cure Electrification", "Healing"],
    "exana pox" => ["Cure Poison", "Healing"],
    "adana pox" => ["Cure Poison Rune", "Support"],
    "utori mort" => ["Curse", "Attack"],
    "exori mort" => ["Death Strike", "Attack"],
    "adito grav" => ["Destroy Field Rune", "Support"],
    "adito tera" => ["Disintegrate Rune", "Support"],
    "exevo mas san" => ["Divine Caldera", "Attack"],
    "exana amp res" => ["Divine Dazzle", "Support"],
    "utevo grav san" => ["Divine Empowerment", "Support"],
    "exevo tempo mas san" => ["Divine Grenade", "Attack"],
    "exura san" => ["Divine Healing", "Healing"],
    "exori san" => ["Divine Missile", "Attack"],
    "utori vis" => ["Electrify", "Attack"],
    "utori mas sio" => ["Enchant Party", "Support"],
    "exeta con" => ["Enchant Spear", "Support"],
    "exevo vis lux" => ["Energy Beam", "Attack"],
    "adevo mas vis" => ["Energy Bomb Rune", "Support"],
    "adevo grav vis" => ["Energy Field Rune", "Support"],
    "exori vis" => ["Energy Strike", "Attack"],
    "adevo mas grav vis" => ["Energy Wall Rune", "Support"],
    "exevo vis hur" => ["Energy Wave", "Attack"],
    "utori pox" => ["Envenom", "Attack"],
    "exevo gran mas frigo" => ["Eternal Winter", "Attack"],
    "exori con" => ["Ethereal Spear", "Attack"],
    "exori amp kor" => ["Executioner's Throw", "Attack"],
    "adevo mas hur" => ["Explosion Rune", "Support"],
    "exori moe" => ["Expose Weakness", "Support"],
    "exura med ico" => ["Fair Wound Cleansing", "Healing"],
    "exori gran" => ["Fierce Berserk", "Attack"],
    "exiva moe res" => ["Find Fiend", "Support"],
    "exiva" => ["Find Person", "Support"],
    "adevo mas flam" => ["Fire Bomb Rune", "Support"],
    "adevo grav flam" => ["Fire Field Rune", "Support"],
    "adevo mas grav flam" => ["Fire Wall Rune", "Support"],
    "exevo flam hur" => ["Fire Wave", "Attack"],
    "adori flam" => ["Fireball Rune", "Support"],
    "exori flam" => ["Flame Strike", "Attack"],
    "exevo pan" => ["Food", "Support"],
    "exori min" => ["Front Sweep", "Attack"],
    "exevo max mort" => ["Great Death Beam", "Attack"],
    "exevo gran vis lux" => ["Great Energy Beam", "Attack"],
    "exevo gran flam hur" => ["Great Fire Wave", "Attack"],
    "adori gran" => ["Heavy Magic Missile Rune", "Support"],
    "exevo gran" => ["Great Fire", "Attack"],
    "utevo gran lux" => ["Great Light", "Support"],
    "exori mas" => ["Groundshaker", "Attack"],
    "utani hur" => ["Haste", "Support"],
    "exura sio" => ["Heal Friend", "Healing"],
    "utura mas sio" => ["Heal Party", "Support"],
    "adori vis" => ["Heavy Magic Missile Rune", "Support"],
    "exevo gran mas flam" => ["Hell's Core", "Attack"],
    "utori san" => ["Holy Flash", "Attack"],
    "adori san" => ["Holy Missile Rune", "Support"],
    "exevo ulus frigo" => ["Ice Burst", "Attack"],
    "exori frigo" => ["Ice Strike", "Attack"],
    "exevo frigo hur" => ["Ice Wave", "Attack"],
    "adori" => ["Light Magic Missile Rune", "Support"],
    "utori flam" => ["Ignite", "Attack"],
    "utori kor" => ["Inflict Wound", "Attack"],
    "exura gran" => ["Intense Healing", "Healing"],
    "adura gran" => ["Intense Healing Rune", "Support"],
    "utura gran" => ["Intense Recovery", "Healing"],
    "exura gran ico" => ["Intense Wound Cleansing", "Healing"],
    "utana vid" => ["Invisible", "Support"],
    "exori infir con" => ["Lesser Ethereal Spear", "Attack"],
    "exori infir min" => ["Lesser Front Sweep", "Attack"],
    "exani hur" => ["Levitate", "Support"],
    "utevo lux" => ["Light", "Support"],
    "exura" => ["Light Healing", "Healing"],
    "adori min vis" => ["Light Magic Missile Rune", "Support"],
    "exori amp vis" => ["Lightning", "Attack"],
    "exura infir" => ["Magic Patch", "Healing"],
    "exani tera" => ["Magic Rope", "Support"],
    "utamo vita" => ["Magic Shield", "Support"],
    "adevo grav tera" => ["Magic Wall Rune", "Support"],
    "exura gran mas res" => ["Mass Healing", "Healing"],
    "exevo ulus tera" => ["Mud Attack", "Attack"],
    "exura gran sio" => ["Nature's Embrace", "Healing"],
    "adana ani" => ["Paralyse Rune", "Support"],
    "exori moe ico" => ["Physical Strike", "Attack"],
    "adevo res pox" => ["Envenom Rune", "Support"],
    "adevo grav pox" => ["Poison Field Rune", "Support"],
    "adevo mas grav pox" => ["Poison Wall Rune", "Support"],
    "adevo mas pox" => ["Poison Bomb Rune ", "Support"],
    "utamo mas sio" => ["Protect Party", "Support"],
    "utamo tempo" => ["Protector", "Support"],
    "exevo gran mas vis" => ["Rage of the Skies", "Attack"],
    "utura" => ["Recovery", "Healing"],
    "exura max vita" => ["Restoration", "Healing"],
    "exura gran san" => ["Salvation", "Healing"],
    "exori kor" => ["Sap Strength", "Support"],
    "exevo infir flam hur" => ["Scorch", "Attack"],
    "utito tempo san" => ["Sharpshooter", "Support"],
    "adevo res flam" => ["Soulfire Rune", "Support"],
    "adori tera" => ["Stalagmite Rune", "Support"],
    "exura si" => ["Support Healing", "Healing"],
    "adana sio" => ["Support Rune", "Support"],
    "adori vita vis" => ["Sudden Death Rune", "Attack"],
    "adevo grav vita" => ["Wild Growth Rune", "Attack"],
    "adura vita" => ["Ultimate Healing Rune", "Attack"],
    "adori gran flam" => ["Great Fireball Rune", "Attack"]

];

$runasRetronia = [

    "adana mort" => ["name" => "Animate Dead Rune", "mlvl" => 2, "vocation" => "Druid, Knight, Paladin, Sorcerer", "description" => "This is a very scary spell. The magicians of Edron have studied captured undead creatures for a long time in order to explore their eerie secret. Finally, they succeeded in storing some life energy in a rune. When this energy was unleashed onto a body it was found that an undead creature arose that could be mentally controlled by the user of the rune. This spell is useful to create allies in combat without having to resort to the expensive summoning spell."],

    "adana pox" => ["name" => "Antidote Rune", "mlvl" => 0, "vocation" => "Druid, Knight, Paladin, Sorcerer", "description" => "In the old days, when the world was still young and people did not know the dangers of the wild, many adventurers fell prey to poisonous creatures that were roaming the caves and forests. The druids, who were skilled with all kinds of poisons, wanted to help those young adventurers that were not able to cure themselves. After many years of research they finally succeeded in altering the cure poison spell so it could be bound to a rune. By using this rune it was possible to stop the effect of any known poison. Ever since then, the trusty cure poison rune has saved the life of many a poisoned adventurer who found he had run out of mana just when he needed it most."], 

    "adori gran frigo" => ["name" => "Avalanche Rune", "mlvl" => 5, "vocation" => "Druid, Knight, Paladin, Sorcerer", "description" => "The Avalanche rune rolls over its victims just like its name giver. It is just as cold as an icicle rune but with up to 37 squares it affects a much greater area. The ice damage which arises from this rune is a useful weapon in every battle but it comes in particularly handy if you fight against a horde of creatures dominated by the element fire. Once it is released, everybody standing near the rune user will feel the gruesome pain this freezing magic is causing. This rune is popular among all vocations even though only druids are able to fill empty magical stones with this powerful spell."],

    "" => ["name" => "Blank Rune", "mlvl" => 0, "vocation" => "", "description" => ""],

    "adevo ina" => ["name" => "Chameleon Rune", "mlvl" => 4, "vocation" => "Druid, Knight, Paladin, Sorcerer", "description" => "This peculiar rune spell was more or less discovered by accident. Legend has it that the famous druid Ferdo the Forgetful tested a new healing spell on himself to cure his toothache, only to find that he was turned into a flowerpot! However, the metamorphosis caused by Chameleon is only superficial, and while a caster who is using the spell can take on the exterior form of nearly any inanimate object, he will always retain his original smell and mental abilities. While this proved to be good luck for Ferdo, it clearly showed the spell's limitations. Very few creatures and only the most distracted of intelligent beings are fooled by Chameleon, so there is no practical use for it, making this largely a fun spell. However, some of the foremost of today's druids are still researching the spell, so it is to be hoped that one day the spell's evident flaws can be removed."],

    "adeta sio" => ["name" => "Convince Creature Rune", "mlvl" => 5, "vocation" => "Druid, Knight, Paladin, Sorcerer", "description" => "The Convince Creature rune was developed by druids who wished to find a way to befriend hostile animals rather than having to kill them. It soon turned out, however, that this rune could also be used against more powerful creatures, including some who must actually be considered to be intelligent species. Unfortunately, to succeed in convincing a creature mana, additionally to creating the rune, has to be spent. The mental strain on the user of the rune is determined by the power of the creature he wishes to convince, so the amount of mana to convince a rat is lower than that which is needed for an orc. The adventurer who uses the rune should make sure in advance, however, that the target is really susceptible to the effect of this spell - there is no point in trying to convince a rampaging dragon. Also, the adventurer should make sure to stay close to convinced creatures to maintain the bond. Convinced creatures that are separated from their masters will soon run off, never to be seen again."],

    "adito tera" => ["name" => "Desintegrate Rune", "mlvl" => 4, "vocation" => "Druid, Knight, Paladin, Sorcerer", "description" => "Nothing is worse than being cornered when fleeing from an enemy you just cannot beat, especially if the obstacles in your way are items you could easily remove if only you had the time! However, there is one reliable remedy: The Disintegrate rune will instantly destroy up to 500 movable items that are in your way, making room for a quick escape. If you need to run for it and you do not have the time to smash an obstacle in your way, the Disintegrate rune is what you need. You should always make sure to have a few of them in your backpack!"], 

    "adito grav" => ["name" => "Destroy Field Rune", "mlvl" => 3, "vocation" => "Druid, Knight, Paladin, Sorcerer", "description" => "In the world of Tibia, magical fields are a common threat. Not only do many adventurers have the possibility to use field runes, but there are also a number of other conceivable causes, including traps, breath attacks by certain creatures and even perfectly natural occurrences. To be trapped by such harmful fields is an unpleasant experience most seasoned adventurers have had at some point or other. Many of them simply owe their survival to having had a couple of Destroy Field runes with them! A truly indispensable spell, this rune should not miss in any adventurer's backpack."], 

    "adevo mas vis" => ["name" => "Energy Bomb Rune", "mlvl" => 10, "vocation" => "Druid, Knight, Paladin, Sorcerer", "description" => "Another spell devised by the crafty sorcerers in Edron's magic academy, the development of the Energy Bomb was based on the trusty Energy Field spell. As with its weaker relative, using the Energy Bomb rune will create a field of deadly energy that deals damage to all who carelessly step into it. However, its area of effect has been greatly enhanced, now covering a full 9 square metres! Monsters that are caught in the middle of an Energy Bomb are frequently confused by the unexpected effect, and some may even stay in the field of deadly sparks for a while. Also, some daring adventurers are known to use the Energy Bomb onto themselves in desperate situations to keep their enemies from attacking them. However, for obvious reasons only the strongest or most desperate of adventurers should use energy bombs this way. Please note that on optional PvP game worlds this spell has no damaging effect on other characters, unless characters are war opponents."], 

    "adevo grav vis" => ["name" => "Energy Field Rune", "mlvl" => 3, "vocation" => "Druid, Knight, Paladin, Sorcerer", "description" => "One of the standard field runes, this spell creates a limited barrier made up of crackling energy that will cause electrical damage to all those passing through. Since there are few creatures that are immune to the harmful effects of energy this spell is not to be underestimated. In fact, rather than using the rune to block narrow passageways, many of the more inexperienced Tibians use it as a cheap offensive spell, since affected creatures suffer energy damage at least twice. Please note that on optional PvP game worlds this spell has no damaging effect on other characters, unless characters are war opponents."], 

    "adevo mas grav vis" => ["name" => "Energy Wall Rune", "mlvl" => 9, "vocation" => "Druid, Knight, Paladin, Sorcerer", "description" => "Casting this spell generates a solid wall made up of magical energy. Walls made this way surpass any other magically created obstacle in width, so they are recommended for use in outside areas where there are powerful monsters to run away from. For this reason it is always a good idea to have an Energy Wall rune or two in one's pocket when travelling through the wilderness. However, recent studies have suggested that there may be some creatures that are capable of breaking through energy walls, so you should always be prepared for a quick escape just in case. Please note that on optional PvP game worlds this spell has no damaging effect on other characters, unless characters are war opponents."],

    "adevo res pox" => ["name" => "Envenom Rune", "mlvl" => 4, "vocation" => "Druid, Knight, Paladin, Sorcerer", "description" => "The Envenom Rune is a powerful tool that inflicts poison damage over time on enemies. Useful for weakening foes or controlling areas, it requires advanced magic skills to create and use effectively. Typically favored by Druids and Sorcerers."],

    "adevo mas hur" => ["name" => "Explosion Rune", "mlvl" => 6, "vocation" => "Druid, Knight, Paladin, Sorcerer", "description" => "
    The Explosion rune is somewhat unusual. It must be aimed at areas rather than at specific creatures, so it is possible for explosions to be unleashed even if no targets are close at all. For this reason the effective use of the rune requires some skill. Thankfully, however, explosions cause damage within a substantial blast radius, so the experienced adventurer will know when and how to use this spell to achieve optimal results. In spite of its tricky handling Explosion is still an immensely popular spell as it deals considerable physical damage and because it is the most powerful attack spell druids can bind into runes.
    "],

    "adevo grav flam" => ["name" => "Fire Field Rune", "mlvl" => 1, "vocation" => "Druid, Knight, Paladin, Sorcerer", "description" => "One of the earliest spells ever to be developed, this is a reliable, no-nonsense field spell that is based on fire. When the rune is used a field of approximately one square metre is covered by searing fire that will last for some minutes, gradually diminishing as the blaze wears down. As with all field spells, Fire Field is quite useful to block narrow passageways or to create large, connected barriers. Placing the field on an opponent is also a strategy that will work well with weaker monsters, although most stronger creatures will easily shake off the effect.
    Please note that on optional PvP game worlds this spell has no damaging effect on other characters, unless characters are war opponents."], 

    "adevo mas grav flam" => ["name" => "Fire Wall Rune", "mlvl" => 6, "vocation" => "Druid, Knight, Paladin, Sorcerer", "description" => "The Fire Wall spell is one of the oldest known enchantments, and it has proved its worth on countless occasions. It offers reliable protection against all creatures that are afraid of fire, and many an adventurer who travels through the wilderness uses these runes to make sure he gets some undisturbed rest. The exceptionally long duration of the spell as well as the possibility to form massive barriers or even protective circles out of fire walls make this a versatile, practical spell that should not miss in any druid's or sorcerer's spellbook. Please note that on optional PvP game worlds this spell has no damaging effect on other characters, unless characters are war opponents."], 

    "adori flam" => ["name" => "Fireball Rune", "mlvl" => 2, "vocation" => "Druid, Knight, Paladin, Sorcerer", "description" => "Without any doubt Fireball is one of the most common attack runes there are in Tibia. Ever since its spell was developed, this reliable rune has proven its worth in countless battles. When it is used a massive fiery ball is released which hits the aimed foe with immense power. It is especially effective against opponents of the element earth. On the other hand, opponents that resist fire well can easily shake off the spell's effects. Today, the Fireball spell has somewhat lost in attractiveness since an improved version, the Great Fireball, was released. However, the traditional Fireball spell is still common due to its lower mana and magic level requirements."], 

    "adevo mas flam" => ["name" => "Firebomb Rune", "mlvl" => 5, "vocation" => "Druid, Knight, Paladin, Sorcerer", "description" => "A cunning combination of the Fireball and Fire Field spells, this rune is a deadly weapon in the hands of the skilled user. On releasing it an area of 9 square metres is covered by searing flames that will scorch all those that are unfortunate enough to be caught in them. Worse, many monsters are confused by the unexpected blaze, and with a bit of luck a caster will even manage to trap his opponents by using the spell. However, caution is needed since most of the more determined monsters or creatures will not be held back by the flames for long. Some daring adventurers are known to have used Fire Bomb runes onto themselves in desperate situations to keep their enemies from attacking them. However, for obvious reasons only the strongest or most desperate adventurers should use fire bombs this way. Please note that on optional PvP game worlds this spell has no damaging effect on other characters, unless characters are war opponents."], 

    "adori gran flam" => ["name" => "Great Fireball Rune", "mlvl" => 4, "vocation" => "Druid, Knight, Paladin, Sorcerer", "description" => "As may be taken from the title, the Great Fireball is basically an enlarged version of the trusty Fireball rune. In contrast to the single shot of a Fireball rune, the Great Fireball affects a huge area, up to 37 square metres! This way any average sized room is easily filled with the searing blaze, scorching all creatures that are in it except for the rune user himself. It stands to reason that the Great Fireball is a favourite of most Tibians, as it is well suited both to hit whole crowds of monsters and individual targets that are difficult to hit because they are fast or hard to spot. There are few adventurers who do not cherish those moments of silent glory when they have just brought down a whole crowd of enemies with a single Great Fireball. Still, due to the large blast radius the users are well advised not to be too trigger happy with this rune to make sure no friend is near when it is used."], 

    "adori gran" => ["name" => "Heavy Magic Missile Rune", "mlvl" => 3, "vocation" => "Druid, Knight, Paladin, Sorcerer", "description" => "Heavy Magic Missile is perhaps the standard attack spell rune in Tibia. As with its lesser relative, the Light Magic Missile, this spell is bound onto blank runes which may be used up to 10 times each in order to hurl massive balls of concentrated magical energy at one or several opponents. A true classic that should not miss in any spell caster's book, Heavy Magic Missile is popular both with beginners and with masters of sorcery alike as the damage that is inflicted is largely determined by the caster's skill and experience, making this an economical, reliable attack spell. Keep in mind, however, that there are a number of creatures that are immune to the damaging effect of magical energy."], 

    "adori frigo" => ["name" => "Icicle Rune", "mlvl" => 4, "vocation" => "Druid, Knight, Paladin, Sorcerer", "description" => "As only druids are skilled enough to control the element ice completely, it was them that developed a rune with a freezing effect. Especially creatures determined by the element fire are vulnerable against this ice-cold rune. Being hit by the magic stored in this rune, an ice arrow seems to pierce the heart of the struck victim. Cold is pervading the body which is so immense that it is taking the breath away. The damage done by this rune is quite impressive which makes this a quite popular rune among Tibian mages."],

    "adura gran" => ["name" => "Intense Healing Rune", "mlvl" => 1, "vocation" => "Druid, Knight, Paladin, Sorcerer", "description" => "This rune was the first result of the druids' efforts to bind their healing magic into spell runes. The primary aim was to give a greater measure of independence to knights whose poor magic skills rarely sufficed to heal the wounds they received in battle. However, there was a need for readily available healing magic among all vocations, as there was always the danger of running out of mana in dangerous situations. For this reason the Intense Healing Rune was hailed as a big achievement by all Tibian adventurers, and it was soon found in every adventurer's backpack. Today, however, the rune is no longer as popular, since it was replaced by the much more efficient Ultimate Healing Rune. However, it is still commonly used by young adventurers who are not skilled enough yet to use the famous blue runes. Also, since the rune's effectiveness is determined by the user's magic skill it is still popular among experienced spell casters who use it to get effective healing magic at a cheap price. Please note that on optional PvP game worlds, the rune has no effect on wild creatures."], 

    "adori" => ["name" => "Light Magic Missile Rune", "mlvl" => 0, "vocation" => "Druid, Knight, Paladin, Sorcerer", "description" => "The Light Magic Missile spell is usually the first attack rune spell to be found in a beginner's spellbook. By casting it onto a blank rune in his hand, the caster will create a beautiful green rune that can be used up to ten times against an opponent. The Light Magic Missile itself is an energy blast that will cause moderate damage on the target. Spell casters usually abandon this spell as soon as they are capable of creating the more powerful Heavy Magic Missile runes. However, as the damage caused by the rune is determined by the skill of its user, the Light Magic Missile rune can cause surprising damage in the hands of an expert caster."],

    "adevo grav tera" => ["name" => "Magic Wall Rune", "mlvl" => 9, "vocation" => "Druid, Knight, Paladin, Sorcerer", "description" => "This spell causes all particles that are contained in the surrounding air to quickly gather and contract until a solid wall is formed that covers one full square metre. The wall that is formed that way is impenetrable to any missiles or to light and no creature or character can walk through it. However, the wall will only last for a couple of seconds before it evaporates just as though it had never existed. It is always a good idea to have a magic wall rune or two in your backpack in case you are chased by a monster you just cannot hope to defeat. On open PvP game world, magic walls can also be yellowish. The yellow tone appears to all characters who are not in a PvP situation with the casting character. Characters can simply walk through these yellowish walls.On optional PvP game worlds, magic walls are mostly yellowish and will collapse if somebody walks on a field with a magic wall. The only exception are magic walls cast by one of your opponents if you are involved in a guild war. These magic walls will last just as long as on other game world types, or until somebody who is not a war opponent of the casting character walks against it.
    "], 

    "adana ani" => ["name" => "Paralyze Rune", "mlvl" => 18, "vocation" => "Druid", "description" => "The Paralyse spell was devised by the legendary druid Arthiniel the Absent-minded. Having extensively researched the arcane art of alchemy, a field of traditional expertise of all druids, Arthiniel found a way to instantly solidify fluids by using magic. Looking for a practical application for his discovery, Arthiniel managed to bind the spell into a rune that could be used against an unsuspecting opponent in combat. The effect of the spell causes the target's blood to thicken, leaving him paralysed and unable to fight or escape unless the effect has worn off. Today, the spell is rarely being used because it has a number of drawbacks. For instance, its effect can easily be broken by any form of healing magic, and quite a number of Tibia's monstrosities are simply immune to it. Worse, Paralyse requires the massive use of mana both during the creation of the rune and during its application, making this an uncommonly expensive spell. However, despite these disadvantages the spell has obvious potential since it is almost sure to buy its user precious time in combat.On optional PvP game worlds, you can only paralyse characters with whom you are at war."],

    "adevo mas pox" => ["name" => "Poison Bomb Rune", "mlvl" => 4, "vocation" => "Druid, Knight, Paladin, Sorcerer", "description" => "Another product of the druids' continual research into poisons, this rune represents an advancement of the Poison Field. Like its lesser relative, the rune causes an area to be contaminated with toxic gas that will poison anybody who is caught within it. However, the area of effect of the rune has been improved - now a full 9 square metres are contaminated. Conceivable applications include the blocking of areas or the combat against fast-moving or invisible targets. Keep in mind, however, that there are a number of creatures that are immune to poison. Please note that on optional PvP game worlds this spell has no damaging effect on other characters, unless characters are war opponents."], 

    "adevo grav pox" => ["name" => "Poison Field Rune", "mlvl" => 1, "vocation" => "Druid, Knight, Paladin, Sorcerer", "description" => "After careful study of the existing varieties, the druids came up with this contribution to the field spell arsenal. Making use of their pre-eminent knowledge of all kinds of toxins they devised a way to create small pockets of poison gas which remain stable for several minutes before dissipating. Anybody who enters these fields will be affected by a vicious toxin. Consequently, many creatures will avoid them, although strong monsters or creatures that are immune to poison will not hesitate to move into them. Still, the spell is usually well suited to create protective barriers. Also, its usefulness as a cheap attack spell to be cast on weaker creatures must not be underestimated. Please note that on optional PvP game worlds this spell has no damaging effect on other characters, unless characters are war opponents."], 

    "adevo mas grav pox" => ["name" => "Poison Wall Rune", "mlvl" => 5, "vocation" => "Druid, Knight, Paladin, Sorcerer", "description" => "The poison wall rune is probably the most basic of all wall spells, and it is frequently the first one to be studied by those who have just taken up the study of magic. When this rune is used a wall of concentrated toxic fumes is created which inflicts a moderate poison on all those who are foolish enough to enter it. The effect is usually impressive enough to discourage monsters from doing so, although few of the stronger monstrosities that walk the land will hesitate if there is nothing but a poison wall between them and their dinner. For this reason it is advisable not to completely rely on this rune for protection, although there is no doubt that a clever adventurer can put it to use quite often. Please note that on optional PvP game worlds this spell has no damaging effect on other characters, unless characters are war opponents."],

    "adevo res flam" => ["name" => "Soulfire Rune", "mlvl" => 7, "vocation" => "Druid, Knight, Paladin, Sorcerer", "description" => "Soulfire is an immensely evil spell as it directly targets a creature's very life essence. When the rune is used on a victim its soul is temporarily moved out of its body, casting it down into the blazing fires of hell itself! Needless to say, the process is immensely painful, and the wounds that are inflicted to the target are quite real. Note that the experience and the mental strength of the caster influence the damage that is caused. In the hands of an experienced user the Soulfire rune can become a fearsome weapon indeed."], 

    "adori vita vis" => ["name" => "Sudden Death Rune", "mlvl" => 15, "vocation" => "Druid, Knight, Paladin, Sorcerer", "description" => "The name of this spell and the ominous skull and crossbones on the runes say it all. Fast and deadly, the sorcerers' widespread reputation of gruesome efficiency in combat is largely based on this devastating spell. Nearly no other spell can compare to Sudden Death when it comes to sheer damage. For this reason it is immensely popular despite the fact that only a single target is affected. In fact, most sorcerers and druids and quite a number of skilled paladins always have a couple of Sudden Death runes in their backpacks in case of an unexpected ambush. However, a wary adventurer will not blindly rely on his Sudden Death runes to save him in any position. Since the damage caused by the rune is of deadly nature, it is less useful against most undead creatures. Due to the enormous power that is bound to this strong rune, it can only be used by players who have experience level 45."], 

    "adura vita" => ["name" => "Ultimate Healing Rune", "mlvl" => 4, "vocation" => "Druid, Knight, Paladin, Sorcerer", "description" => "The coveted Ultimate Healing rune is an all-time favourite among all vocations. No other healing enchantments that are bound into runes can compare to its salutary effect. For this reason the secret knowledge of how to create these precious runes is jealously guarded by the druids. Surely, particularly knights and paladins will rather use instant spells in critical situations, but once you are out of mana you are well advised to have a backpack of Ultimate Healing runes at hand. Please note that on optional PvP game worlds, the rune has no effect on wild creatures."],
];

$spells = [
    [
        'needLearn' => true,
        'mana' => 20,
        'magicLevel' => 3,
        'name' => 'Flame Strike',
        'vocation' => ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid'],
        'category' => 'instant',
        'words' => 'exori flam',
        'isPremium' => true,
    ],
    [
        'needLearn' => true,
        'mana' => 100,
        'magicLevel' => 10,
        'name' => 'Energy Beam',
        'vocation' => ['Sorcerer', 'Master Sorcerer'],
        'category' => 'instant',
        'words' => 'exevo vis lux',
    ],
    [
        'needLearn' => true,
        'mana' => 20,
        'magicLevel' => 2,
        'name' => 'Force Strike',
        'vocation' => ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid'],
        'category' => 'instant',
        'words' => 'exori mort',
        'isPremium' => true,
    ],
    [
        'needLearn' => true,
        'mana' => 200,
        'magicLevel' => 14,
        'name' => 'Great Energy Beam',
        'vocation' => ['Sorcerer', 'Master Sorcerer'],
        'category' => 'instant',
        'words' => 'exevo gran vis lux',
    ],
    [
        'needLearn' => true,
        'mana' => 600,
        'magicLevel' => 28,
        'name' => 'Poison Storm',
        'vocation' => ['Druid', 'Elder Druid'],
        'category' => 'instant',
        'words' => 'exevo gran mas pox',
        'isPremium' => true,
    ],
    [
        'needLearn' => true,
        'mana' => 800,
        'magicLevel' => 40,
        'name' => 'Ultimate Explosion',
        'vocation' => ['Sorcerer', 'Master Sorcerer'],
        'category' => 'instant',
        'words' => 'exevo gran mas vis',
        'isPremium' => true,
    ],
    [
        'needLearn' => true,
        'mana' => 80,
        'magicLevel' => 7,
        'name' => 'Fire Wave',
        'vocation' => ['Sorcerer', 'Master Sorcerer'],
        'category' => 'instant',
        'words' => 'exevo flam hur',
    ],
    [
        'needLearn' => true,
        'magicLevel' => 5,
        'name' => 'Berserk',
        'vocation' => ['Knight', 'Elite Knight'],
        'category' => 'instant',
        'words' => 'exori',
        'isPremium' => true,
        'manaPercent' => 80,
    ],
    [
        'needLearn' => true,
        'mana' => 250,
        'magicLevel' => 20,
        'name' => 'Energy Wave',
        'vocation' => ['Sorcerer', 'Master Sorcerer'],
        'category' => 'instant',
        'words' => 'exevo mort hur',
        'isPremium' => true,
    ],
    [
        'needLearn' => true,
        'mana' => 20,
        'magicLevel' => 3,
        'name' => 'Energy Strike',
        'vocation' => ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid'],
        'category' => 'instant',
        'words' => 'exori vis',
        'isPremium' => true,
    ],
    [
        'needLearn' => true,
        'mana' => 70,
        'magicLevel' => 6,
        'soul' => 0,
        'name' => 'Conjure Bolt',
        'vocation' => ['Paladin', 'Royal Paladin'],
        'category' => 'conjuring',
        'words' => 'exevo con mort',
        'conjureAmount' => 10,
    ],
    [
        'needLearn' => true,
        'mana' => 30,
        'magicLevel' => 0,
        'name' => 'Food',
        'vocation' => ['Druid', 'Elder Druid', 'Paladin', 'Royal Paladin'],
        'category' => 'conjuring',
        'words' => 'exevo pan',
    ],
    [
        'needLearn' => true,
        'mana' => 40,
        'magicLevel' => 2,
        'soul' => 0,
        'name' => 'Conjure Arrow',
        'vocation' => ['Paladin', 'Royal Paladin'],
        'category' => 'conjuring',
        'words' => 'exevo con',
        'conjureAmount' => 15,
    ],
    [
        'needLearn' => true,
        'mana' => 200,
        'magicLevel' => 14,
        'soul' => 0,
        'name' => 'Conjure Power Bolt',
        'vocation' => ['Royal Paladin'],
        'category' => 'conjuring',
        'words' => 'exevo con vis',
        'isPremium' => true,
        'conjureAmount' => 1,
    ],
    [
        'needLearn' => true,
        'mana' => 70,
        'magicLevel' => 5,
        'soul' => 0,
        'name' => 'Poisoned Arrow',
        'vocation' => ['Paladin', 'Royal Paladin'],
        'category' => 'conjuring',
        'words' => 'exevo con pox',
        'conjureAmount' => 10,
    ],
    [
        'needLearn' => true,
        'mana' => 120,
        'magicLevel' => 10,
        'soul' => 0,
        'name' => 'Explosive Arrow',
        'vocation' => ['Paladin', 'Royal Paladin'],
        'category' => 'conjuring',
        'words' => 'exevo con flam',
        'isPremium' => true,
        'conjureAmount' => 5,
    ],
    [
        'needLearn' => true,
        'mana' => 80,
        'magicLevel' => 22,
        'soul' => 0,
        'name' => 'Enchant Staff',
        'vocation' => ['Master Sorcerer'],
        'category' => 'conjuring',
        'words' => 'exeta vis',
        'isPremium' => true,
        'conjureAmount' => 1,
    ],
    [
        'needLearn' => true,
        'mana' => 70,
        'magicLevel' => 7,
        'name' => 'Heal Friend',
        'vocation' => ['Druid', 'Elder Druid'],
        'category' => 'instant',
        'words' => 'exura sio',
        'isPremium' => true,
    ],
    [
        'needLearn' => true,
        'mana' => 40,
        'magicLevel' => 2,
        'name' => 'Intense Healing',
        'vocation' => ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid', 'Paladin', 'Royal Paladin'],
        'category' => 'instant',
        'words' => 'exura gran',
    ],
    [
        'needLearn' => true,
        'mana' => 30,
        'magicLevel' => 7,
        'name' => 'Light Heal Friend',
        'vocation' => ['Druid', 'Elder Druid'],
        'category' => 'instant',
        'words' => 'exana sio',
        'isPremium' => true,
    ],
    [
        'needLearn' => true,
        'mana' => 120,
        'magicLevel' => 19,
        'name' => 'Mass Healing',
        'vocation' => ['Druid', 'Elder Druid'],
        'category' => 'instant',
        'words' => 'exura gran mas res',
        'isPremium' => true,
    ],
    [
        'needLearn' => true,
        'mana' => 80,
        'magicLevel' => 8,
        'name' => 'Ultimate Healing',
        'vocation' => ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid', 'Paladin', 'Royal Paladin'],
        'category' => 'instant',
        'words' => 'exura vita',
    ],
    [
        'needLearn' => true,
        'mana' => 25,
        'magicLevel' => 1,
        'name' => 'Light Healing',
        'vocation' => ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid', 'Paladin', 'Royal Paladin', 'Knight', 'Elite knight'],
        'category' => 'instant',
        'words' => 'exura',
    ],
    [
        'needLearn' => true,
        'mana' => 50,
        'magicLevel' => 2,
        'soul' => 0,
        'name' => 'Poison Field',
        'vocation' => ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid'],
        'category' => 'rune',
        'words' => 'adevo grav pox',
        'runeMagicLevel' => 0,
        'runeId' => 2285,
        'charges' => 3,
        'conjureAmount' => 3,
    ],
    [
        'needLearn' => true,
        'mana' => 60,
        'magicLevel' => 5,
        'soul' => 0,
        'name' => 'Fireball',
        'vocation' => ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid', 'Paladin', 'Royal Paladin'],
        'category' => 'rune',
        'words' => 'adori flam',
        'runeMagicLevel' => 2,
        'runeId' => 2302,
        'charges' => 3,
        'isAggressive' => true,
        'conjureAmount' => 3,
    ],
    [
        'needLearn' => true,
        'mana' => 100,
        'magicLevel' => 8,
        'soul' => 0,
        'name' => 'Desintegrate',
        'vocation' => ['Druid', 'Elder Druid', 'Paladin', 'Royal Paladin', 'Sorcerer', 'Master Sorcerer'],
        'category' => 'rune',
        'words' => 'adito tera',
        'runeMagicLevel' => 4,
        'runeId' => 2310,
        'charges' => 3,
        'isAggressive' => true,
        'conjureAmount' => 3,
    ],
    [
        'needLearn' => true,
        'mana' => 100,
        'magicLevel' => 7,
        'soul' => 0,
        'name' => 'Envenom',
        'vocation' => ['Druid', 'Elder Druid'],
        'category' => 'rune',
        'words' => 'adevo res pox',
        'isPremium' => true,
        'runeMagicLevel' => 4,
        'runeId' => 2292,
        'charges' => 3,
        'conjureAmount' => 3,
    ],
    [
        'needLearn' => true,
        'mana' => 220,
        'magicLevel' => 25,
        'soul' => 0,
        'name' => 'Sudden Death',
        'vocation' => ['Sorcerer', 'Master Sorcerer'],
        'category' => 'rune',
        'words' => 'adori vita vis',
        'runeMagicLevel' => 15,
        'runeId' => 2268,
        'charges' => 1,
        'isAggressive' => true,
        'conjureAmount' => 1,
    ],
    [
        'needLearn' => true,
        'mana' => 130,
        'magicLevel' => 8,
        'soul' => 0,
        'name' => 'Poisonbomb',
        'vocation' => ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid'],
        'category' => 'rune',
        'words' => 'adevo mas pox',
        'isPremium' => true,
        'runeMagicLevel' => 4,
        'runeId' => 2286,
        'charges' => 2,
        'conjureAmount' => 2,
    ],
    [
        'needLearn' => true,
        'mana' => 250,
        'magicLevel' => 14,
        'soul' => 0,
        'name' => 'Magic Wall',
        'vocation' => ['Sorcerer', 'Master Sorcerer'],
        'category' => 'rune',
        'words' => 'adevo grav tera',
        'isPremium' => true,
        'runeMagicLevel' => 9,
        'runeId' => 2293,
        'charges' => 4,
        'isAggressive' => true,
        'conjureAmount' => 4,
    ],
    [
        'needLearn' => true,
        'mana' => 250,
        'magicLevel' => 18,
        'soul' => 0,
        'name' => 'Energy Wall',
        'vocation' => ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid'],
        'category' => 'rune',
        'words' => 'adevo mas grav vis',
        'isPremium' => true,
        'runeMagicLevel' => 9,
        'runeId' => 2279,
        'charges' => 4,
        'conjureAmount' => 4,
    ],
    [
        'needLearn' => true,
        'mana' => 150,
        'magicLevel' => 11,
        'soul' => 0,
        'name' => 'Chameleon',
        'vocation' => ['Druid', 'Elder Druid'],
        'category' => 'rune',
        'words' => 'adevo ina',
        'runeMagicLevel' => 4,
        'runeId' => 2291,
        'charges' => 1,
        'isAggressive' => false,
        'conjureAmount' => 1,
    ],
    [
        'needLearn' => true,
        'mana' => 60,
        'magicLevel' => 4,
        'soul' => 0,
        'name' => 'Intense Healing Rune',
        'vocation' => ['Druid', 'Elder Druid'],
        'category' => 'rune',
        'words' => 'adura gran',
        'runeMagicLevel' => 1,
        'runeId' => 2265,
        'charges' => 1,
        'isAggressive' => false,
        'conjureAmount' => 1,
    ],
    [
        'needLearn' => true,
        'mana' => 220,
        'magicLevel' => 18,
        'soul' => 0,
        'name' => 'Energybomb',
        'vocation' => ['Sorcerer', 'Master Sorcerer'],
        'category' => 'rune',
        'words' => 'adevo mas vis',
        'isPremium' => true,
        'runeMagicLevel' => 10,
        'runeId' => 2262,
        'charges' => 2,
        'conjureAmount' => 2,
    ],
    [
        'needLearn' => true,
        'mana' => 300,
        'magicLevel' => 7,
        'soul' => 0,
        'name' => 'Animate Dead',
        'vocation' => ['Sorcerer', 'Master Sorcerer'],
        'category' => 'rune',
        'words' => 'adana mort',
        'runeMagicLevel' => 4,
        'runeId' => 2316,
        'charges' => 2,
        'isAggressive' => false,
        'conjureAmount' => 2,
    ],
    [
        'needLearn' => true,
        'mana' => 180,
        'magicLevel' => 12,
        'soul' => 0,
        'name' => 'Explosion',
        'vocation' => ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid'],
        'category' => 'rune',
        'words' => 'adevo mas hur',
        'runeMagicLevel' => 6,
        'runeId' => 2313,
        'charges' => 3,
        'conjureAmount' => 3,
    ],
    [
        'needLearn' => true,
        'mana' => 60,
        'magicLevel' => 6,
        'soul' => 0,
        'name' => 'Destroy Field',
        'vocation' => ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid', 'Paladin', 'Royal Paladin'],
        'category' => 'rune',
        'words' => 'adito grav',
        'runeMagicLevel' => 3,
        'runeId' => 2261,
        'charges' => 3,
        'isAggressive' => true,
        'conjureAmount' => 3,
    ],
    [
        'needLearn' => true,
        'mana' => 50,
        'magicLevel' => 4,
        'soul' => 0,
        'name' => 'Antidote Rune',
        'vocation' => ['Druid', 'Elder Druid'],
        'category' => 'rune',
        'words' => 'adana pox',
        'runeMagicLevel' => 0,
        'runeId' => 2266,
        'charges' => 1,
        'isAggressive' => false,
        'conjureAmount' => 1,
    ],
    [
        'needLearn' => true,
        'mana' => 40,
        'magicLevel' => 1,
        'soul' => 0,
        'name' => 'Light Magic Missile',
        'vocation' => ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid', 'Paladin', 'Royal Paladin'],
        'category' => 'rune',
        'words' => 'adori',
        'runeMagicLevel' => 0,
        'runeId' => 2287,
        'charges' => 5,
        'conjureAmount' => 5,
    ],
    [
        'needLearn' => true,
        'mana' => 200,
        'magicLevel' => 13,
        'soul' => 0,
        'name' => 'Fire Wall',
        'vocation' => ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid'],
        'category' => 'rune',
        'words' => 'adevo mas grav flam',
        'runeMagicLevel' => 6,
        'runeId' => 2303,
        'charges' => 4,
        'conjureAmount' => 4,
    ],
    [
        'needLearn' => true,
        'mana' => 100,
        'magicLevel' => 10,
        'soul' => 0,
        'name' => 'Convince Creature',
        'vocation' => ['Druid', 'Elder Druid'],
        'category' => 'rune',
        'words' => 'adeta sio',
        'runeMagicLevel' => 5,
        'runeId' => 2290,
        'charges' => 1,
        'conjureAmount' => 1,
    ],
    [
        'needLearn' => true,
        'mana' => 120,
        'magicLevel' => 9,
        'soul' => 0,
        'name' => 'Great Fireball',
        'vocation' => ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid'],
        'category' => 'rune',
        'words' => 'adori gran flam',
        'runeMagicLevel' => 4,
        'runeId' => 2304,
        'charges' => 2,
        'isAggressive' => true,
        'conjureAmount' => 2,
    ],
    [
        'needLearn' => true,
        'mana' => 160,
        'magicLevel' => 11,
        'soul' => 0,
        'name' => 'Poison Wall',
        'vocation' => ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid'],
        'category' => 'rune',
        'words' => 'adevo mas grav pox',
        'runeMagicLevel' => 5,
        'runeId' => 2289,
        'charges' => 4,
        'conjureAmount' => 4,
    ],
    [
        'needLearn' => true,
        'mana' => 70,
        'magicLevel' => 3,
        'soul' => 0,
        'name' => 'Heavy Magic Missile',
        'vocation' => ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid', 'Paladin', 'Royal Paladin'],
        'category' => 'rune',
        'words' => 'adori gran',
        'runeMagicLevel' => 1,
        'runeId' => 2311,
        'charges' => 5,
        'conjureAmount' => 5,
    ],
    [
        'needLearn' => true,
        'mana' => 150,
        'magicLevel' => 9,
        'soul' => 0,
        'name' => 'Firebomb',
        'vocation' => ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid'],
        'category' => 'rune',
        'words' => 'adevo mas flam',
        'runeMagicLevel' => 5,
        'runeId' => 2305,
        'charges' => 2,
        'conjureAmount' => 2,
    ],
    [
        'needLearn' => true,
        'mana' => 100,
        'magicLevel' => 11,
        'soul' => 0,
        'name' => 'Ultimate Healing Rune',
        'vocation' => ['Druid', 'Elder Druid'],
        'category' => 'rune',
        'words' => 'adura vita',
        'runeMagicLevel' => 4,
        'runeId' => 2273,
        'charges' => 1,
        'isAggressive' => false,
        'conjureAmount' => 1,
    ],
    [
        'needLearn' => true,
        'mana' => 80,
        'magicLevel' => 5,
        'soul' => 0,
        'name' => 'Energy Field',
        'vocation' => ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid'],
        'category' => 'rune',
        'words' => 'adevo grav vis',
        'runeMagicLevel' => 3,
        'runeId' => 2277,
        'charges' => 3,
        'conjureAmount' => 3,
    ],
    [
        'needLearn' => true,
        'mana' => 150,
        'magicLevel' => 13,
        'soul' => 0,
        'name' => 'Soulfire',
        'vocation' => ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid'],
        'category' => 'rune',
        'words' => 'adevo res flam',
        'isPremium' => true,
        'runeMagicLevel' => 7,
        'runeId' => 2308,
        'charges' => 2,
        'conjureAmount' => 2,
    ],
    [
        'needLearn' => true,
        'mana' => 600,
        'magicLevel' => 35,
        'soul' => 0,
        'name' => 'Paralyze',
        'vocation' => ['Druid', 'Elder Druid'],
        'category' => 'rune',
        'words' => 'adana ani',
        'isPremium' => true,
        'runeMagicLevel' => 18,
        'runeId' => 2278,
        'charges' => 1,
        'conjureAmount' => 1,
    ],
    [
        'needLearn' => true,
        'mana' => 60,
        'magicLevel' => 3,
        'soul' => 0,
        'name' => 'Fire Field',
        'vocation' => ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid'],
        'category' => 'rune',
        'words' => 'adevo grav flam',
        'runeMagicLevel' => 1,
        'runeId' => 2301,
        'charges' => 3,
        'conjureAmount' => 3,
    ],
    [
        'needLearn' => true,
        'mana' => 210,
        'magicLevel' => 15,
        'name' => 'Invisibility',
        'vocation' => ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid', 'Paladin', 'Royal Paladin'],
        'category' => 'instant',
        'words' => 'utana vid',
    ],
    [
        'needLearn' => true,
        'mana' => 20,
        'magicLevel' => 1,
        'name' => 'Magic Rope',
        'vocation' => ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid', 'Knight', 'Elite Knight', 'Paladin', 'Royal Paladin'],
        'category' => 'instant',
        'words' => 'exani tera',
        'isPremium' => true,
    ],
    [
        'needLearn' => true,
        'mana' => 20,
        'magicLevel' => 0,
        'name' => 'Light',
        'vocation' => ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid', 'Paladin', 'Royal Paladin', 'Knight', 'Elite Knight'],
        'category' => 'instant',
        'words' => 'utevo lux',
    ],
    [
        'needLearn' => true,
        'mana' => 30,
        'magicLevel' => 3,
        'name' => 'Extinguish',
        'vocation' => ['Druid', 'Elder Druid'],
        'category' => 'instant',
        'words' => 'exana flam',
    ],
    [
        'needLearn' => true,
        'mana' => 30,
        'magicLevel' => 3,
        'name' => 'Discharge',
        'vocation' => ['Druid', 'Elder Druid'],
        'category' => 'instant',
        'words' => 'exana vis',
    ],
    [
        'needLearn' => true,
        'mana' => 60,
        'magicLevel' => 3,
        'name' => 'Great Light',
        'vocation' => ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid', 'Paladin', 'Royal Paladin', 'Knight', 'Elite Knight'],
        'category' => 'instant',
        'words' => 'utevo gran lux',
    ],
    [
        'needLearn' => true,
        'mana' => 60,
        'magicLevel' => 4,
        'name' => 'Haste',
        'vocation' => ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid', 'Paladin', 'Royal Paladin', 'Knight', 'Elite knight'],
        'category' => 'instant',
        'words' => 'utani hur',
        'isPremium' => true,
    ],
    [
        'needLearn' => true,
        'mana' => 250,
        'magicLevel' => 12,
        'name' => 'Cancel Invisibility',
        'vocation' => ['Druid', 'Elder Druid'],
        'category' => 'instant',
        'words' => 'exana ina',
        'isPremium' => true,
    ],
    [
        'needLearn' => true,
        'mana' => 150,
        'magicLevel' => 13,
        'soul' => 0,
        'name' => 'Wild Growth',
        'vocation' => ['Elder Druid'],
        'category' => 'instant',
        'words' => 'exevo grav vita',
        'isPremium' => true,
    ],
    [
        'needLearn' => true,
        'mana' => 300,
        'magicLevel' => 15,
        'name' => 'Undead Legion',
        'vocation' => ['Druid', 'Elder Druid'],
        'category' => 'instant',
        'words' => 'exana mas mort',
        'isPremium' => true,
    ],
    [
        'needLearn' => true,
        'mana' => 30,
        'magicLevel' => 2,
        'name' => 'Antidote',
        'vocation' => ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid', 'Paladin', 'Royal Paladin', 'Knight', 'Elite Knight'],
        'category' => 'instant',
        'words' => 'exana pox',
    ],
    [
        'needLearn' => true,
        'mana' => 140,
        'magicLevel' => 12,
        'name' => 'Ultimate Light',
        'vocation' => ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid'],
        'category' => 'instant',
        'words' => 'utevo vis lux',
        'isPremium' => true,
    ],
    [
        'needLearn' => true,
        'mana' => 60,
        'magicLevel' => 7,
        'name' => 'Desintegrate Spell',
        'vocation' => ['Druid', 'Elder Druid'],
        'category' => 'instant',
        'words' => 'exito tera',
    ],
    [
        'needLearn' => true,
        'mana' => 50,
        'magicLevel' => 4,
        'name' => 'Magic Shield',
        'vocation' => ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid', 'Paladin', 'Royal Paladin'],
        'category' => 'instant',
        'words' => 'utamo vita',
    ],
    [
        'needLearn' => true,
        'mana' => 50,
        'magicLevel' => 3,
        'name' => 'Levitate',
        'vocation' => ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid', 'Paladin', 'Royal Paladin', 'Knight', 'Elite Knight'],
        'category' => 'instant',
        'words' => 'exani hur',
        'isPremium' => true,
    ],
    [
        'needLearn' => true,
        'mana' => 30,
        'magicLevel' => 4,
        'name' => 'Challenge',
        'vocation' => ['Knight', 'Elite Knight'],
        'category' => 'instant',
        'words' => 'exeta res',
        'isPremium' => true,
    ],
    [
        'needLearn' => true,
        'mana' => 65,
        'magicLevel' => 10,
        'name' => 'Mass Cleanse',
        'vocation' => ['Druid', 'Elder Druid'],
        'category' => 'instant',
        'words' => 'exana mas res',
        'isPremium' => true,
    ],
    [
        'needLearn' => true,
        'mana' => 100,
        'magicLevel' => 8,
        'name' => 'Strong Haste',
        'vocation' => ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid'],
        'category' => 'instant',
        'words' => 'utani gran hur',
        'isPremium' => true,
    ],
    [
        'needLearn' => true,
        'mana' => 100,
        'magicLevel' => 10,
        'name' => 'Creature Illusion',
        'vocation' => ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid'],
        'category' => 'instant',
        'words' => 'utevo res ina',
        'isPremium' => true,
    ],
    [
        'needLearn' => true,
        'mana' => 0,
        'magicLevel' => 16,
        'name' => 'Summon Creature',
        'vocation' => ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid'],
        'category' => 'instant',
        'words' => 'utevo res',
    ],
    [
        'needLearn' => true,
        'mana' => 20,
        'magicLevel' => 0,
        'name' => 'Find Person',
        'vocation' => ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid', 'Paladin', 'Royal Paladin', 'Knight', 'Elite Knight'],
        'category' => 'instant',
        'words' => 'exiva',
    ],
];

?>